// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovotecDB;

#nullable disable

namespace NovotecDB.Migrations
{
    [DbContext(typeof(AgrarwareConnectorContext))]
    partial class AgrarwareConnectorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovotecDB.AgrarwareConnectorModels.EmployeeConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgrarwareId")
                        .HasColumnType("int");

                    b.Property<long>("NovotecId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("NovotecDB.AgrarwareConnectorModels.GoodsTransportConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgrarwareId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NovotecId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GoodsTransports");
                });

            modelBuilder.Entity("NovotecDB.AgrarwareConnectorModels.TractorConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgrarwareId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NovotecId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Tractors");
                });

            modelBuilder.Entity("NovotecDB.AgrarwareConnectorModels.VehicleConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgrarwareId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NovotecId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
