CREATE TABLE [dbo].[AACTIVE] (
    [AAIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [AAAUIDENT] BIGINT   CONSTRAINT [DF_AACTIVE_AAAUIDENT] DEFAULT ((0)) NOT NULL,
    [AASTATE]   TINYINT  CONSTRAINT [DF_AACTIVE_AASTATE] DEFAULT ((0)) NOT NULL,
    [AASTART]   DATETIME NULL,
    [AAIDLE]    INT      CONSTRAINT [DF_AACTIVE_AAIDLE] DEFAULT ((0)) NOT NULL,
    [AALSTART]  INT      CONSTRAINT [DF_AACTIVE_AALSTART] DEFAULT ((0)) NOT NULL,
    [AALEND]    INT      CONSTRAINT [DF_AACTIVE_AALEND] DEFAULT ((0)) NOT NULL,
    [AADSTART]  DATETIME CONSTRAINT [DF_AACTIVE_AADSTART] DEFAULT (CONVERT([datetime],'2001-01-01T00:00:00',0)) NOT NULL,
    [AADEND]    DATETIME CONSTRAINT [DF_AACTIVE_AADEND] DEFAULT (CONVERT([datetime],'2001-01-01T00:00:00',0)) NOT NULL,
    CONSTRAINT [PK_AACTIVE] PRIMARY KEY CLUSTERED ([AAIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AACTIVE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AACTIVE';

