CREATE TABLE [dbo].[ALIMIT] (
    [ALIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [ALDATE]    DATETIME NULL,
    [ALWHO]     BIGINT   CONSTRAINT [DF_ALIMIT_ALWHO] DEFAULT ((0)) NOT NULL,
    [ALAUIDENT] BIGINT   CONSTRAINT [DF_ALIMIT_ALAUIDENT] DEFAULT ((0)) NOT NULL,
    [ALTYPE]    TINYINT  CONSTRAINT [DF_ALIMIT_ALTYPE] DEFAULT ((0)) NOT NULL,
    [ALLIMIT1]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT1] DEFAULT ((0)) NOT NULL,
    [ALLIMIT2]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT2] DEFAULT ((0)) NOT NULL,
    [ALLIMIT3]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT3] DEFAULT ((0)) NOT NULL,
    [ALLIMIT4]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT4] DEFAULT ((0)) NOT NULL,
    [ALLIMIT5]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT5] DEFAULT ((0)) NOT NULL,
    [ALLIMIT6]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT6] DEFAULT ((0)) NOT NULL,
    [ALLIMIT7]  INT      CONSTRAINT [DF_ALIMIT_ALLIMIT7] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ALIMIT] PRIMARY KEY CLUSTERED ([ALIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ALIMIT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ALIMIT';

