CREATE TABLE [dbo].[AMODPARM] (
    [AMIDENT]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [AMDATE]     DATETIME      CONSTRAINT [DF_AMODPARM_AMDATE] DEFAULT (getdate()) NULL,
    [AMWHO]      BIGINT        CONSTRAINT [DF_AMODPARM_AMWHO] DEFAULT ((0)) NOT NULL,
    [AMAUIDENT]  BIGINT        CONSTRAINT [DF_AMODPARM_AMAUIDENT] DEFAULT ((0)) NOT NULL,
    [AMTEL]      VARCHAR (50)  CONSTRAINT [DF_AMODPARM_AMTEL] DEFAULT ('') NOT NULL,
    [AMIP]       VARCHAR (50)  CONSTRAINT [DF_AMODPARM_AMIP] DEFAULT ('') NOT NULL,
    [AMIPV6]     VARCHAR (50)  CONSTRAINT [DF_AMODPARM_AMIPV6] DEFAULT ('') NOT NULL,
    [AMHOSTNAME] VARCHAR (50)  CONSTRAINT [DF_AMODPARM_AMHOSTNAME] DEFAULT ('') NOT NULL,
    [AMSUBNET]   VARCHAR (50)  CONSTRAINT [DF_AMODPARM_AMSUBNET] DEFAULT ('') NOT NULL,
    [AMCOM]      TINYINT       CONSTRAINT [DF_AMODPARM_AMCOM] DEFAULT ((0)) NOT NULL,
    [AMINIT]     VARCHAR (100) CONSTRAINT [DF_AMODPARM_AMINIT] DEFAULT ('') NOT NULL,
    [AMPULS]     TINYINT       CONSTRAINT [DF_AMODPARM_AMPULS] DEFAULT ((0)) NOT NULL,
    [AMCMD]      VARCHAR (20)  CONSTRAINT [DF_AMODPARM_AMCMD] DEFAULT ('') NOT NULL,
    [AMEND]      VARCHAR (20)  CONSTRAINT [DF_AMODPARM_AMEND] DEFAULT ('') NOT NULL,
    [AMPORT]     INT           CONSTRAINT [DF_AMODPARM_AMPORT] DEFAULT ((0)) NOT NULL,
    [AMOWNPORT]  INT           CONSTRAINT [DF_AMODPARM_AMOWNPORT] DEFAULT ((0)) NOT NULL,
    [AMDATABITS] TINYINT       CONSTRAINT [DF_AMODPARM_AMDATABITS] DEFAULT ((0)) NOT NULL,
    [AMPARITY]   TINYINT       CONSTRAINT [DF_AMODPARM_AMPARITY] DEFAULT ((0)) NOT NULL,
    [AMBAUD]     INT           CONSTRAINT [DF_AMODPARM_AMBAUD] DEFAULT ((0)) NOT NULL,
    [AMXMDELAY]  INT           CONSTRAINT [DF_AMODPARM_AMXMDELAY] DEFAULT ((0)) NOT NULL,
    [AMLRC]      TINYINT       CONSTRAINT [DF_AMODPARM_AMLRC] DEFAULT ((0)) NOT NULL,
    [AMTERM]     TINYINT       CONSTRAINT [DF_AMODPARM_AMTERM] DEFAULT ((0)) NOT NULL,
    [AMUPLOAD]   TINYINT       CONSTRAINT [DF_AMODPARM_AMUPLOAD] DEFAULT ((0)) NOT NULL,
    [AMDOWNLOAD] TINYINT       CONSTRAINT [DF_AMODPARM_AMDOWNLOAD] DEFAULT ((0)) NOT NULL,
    [AMRECREP]   TINYINT       CONSTRAINT [DF_AMODPARM_AMRECREP] DEFAULT ((0)) NOT NULL,
    [AMTRAREP]   TINYINT       CONSTRAINT [DF_AMODPARM_AMTRAREP] DEFAULT ((0)) NOT NULL,
    [AMNACKREP]  TINYINT       CONSTRAINT [DF_AMODPARM_AMNACKREP] DEFAULT ((0)) NOT NULL,
    [AMGSM]      TINYINT       CONSTRAINT [DF_AMODPARM_AMGSM] DEFAULT ((0)) NOT NULL,
    [AMGPRS]     TINYINT       CONSTRAINT [DF_AMODPARM_AMGPRS] DEFAULT ((0)) NOT NULL,
    [AMPROT]     TINYINT       CONSTRAINT [DF_AMODPARM_AMPROT] DEFAULT ((0)) NOT NULL,
    [AMPROTPATH] VARCHAR (MAX) CONSTRAINT [DF_AMODPARM_AMPROTPATH] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_AMODPARM] PRIMARY KEY CLUSTERED ([AMIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AMODPARM';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AMODPARM';

