CREATE TABLE [dbo].[AOPSTAT] (
    [AOIDENT]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [AOAUIDENT]  BIGINT        CONSTRAINT [DF_AOPSTAT_AOAUIDENT] DEFAULT ((0)) NOT NULL,
    [AOCOMDATE]  DATETIME      CONSTRAINT [DF_AOPSTAT_AOCOMDATE] DEFAULT (getdate()) NULL,
    [AOCOMSTATE] SMALLINT      CONSTRAINT [DF_AOPSTAT_AOCOMSTATE] DEFAULT ((-1)) NOT NULL,
    [AOSTAT]     SMALLINT      CONSTRAINT [DF_AOPSTAT_AOSTAT] DEFAULT ((-1)) NOT NULL,
    [AOSTADATE]  DATETIME      CONSTRAINT [DF_AOPSTAT_AOSTADATE] DEFAULT (getdate()) NULL,
    [AOSTAT2]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AOSTAT2] DEFAULT ((-1)) NOT NULL,
    [AOSTA2DATE] DATETIME      CONSTRAINT [DF_AOPSTAT_AOSTA2DATE] DEFAULT (getdate()) NULL,
    [AODISP1]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP1] DEFAULT ((-1)) NOT NULL,
    [AODISP2]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP2] DEFAULT ((-1)) NOT NULL,
    [AODISP3]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP3] DEFAULT ((-1)) NOT NULL,
    [AODISP4]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP4] DEFAULT ((-1)) NOT NULL,
    [AODISP5]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP5] DEFAULT ((-1)) NOT NULL,
    [AODISP6]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP6] DEFAULT ((-1)) NOT NULL,
    [AODISP7]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP7] DEFAULT ((-1)) NOT NULL,
    [AODISP8]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP8] DEFAULT ((-1)) NOT NULL,
    [AODISP9]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP9] DEFAULT ((-1)) NOT NULL,
    [AODISP10]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP10] DEFAULT ((-1)) NOT NULL,
    [AODISP11]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP11] DEFAULT ((-1)) NOT NULL,
    [AODISP12]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP12] DEFAULT ((-1)) NOT NULL,
    [AODISP13]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP13] DEFAULT ((-1)) NOT NULL,
    [AODISP14]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP14] DEFAULT ((-1)) NOT NULL,
    [AODISP15]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP15] DEFAULT ((-1)) NOT NULL,
    [AODISP16]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP16] DEFAULT ((-1)) NOT NULL,
    [AODISP17]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP17] DEFAULT ((-1)) NOT NULL,
    [AODISP18]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP18] DEFAULT ((-1)) NOT NULL,
    [AODISP19]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP19] DEFAULT ((-1)) NOT NULL,
    [AODISP20]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP20] DEFAULT ((-1)) NOT NULL,
    [AODISP21]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP21] DEFAULT ((-1)) NOT NULL,
    [AODISP22]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP22] DEFAULT ((-1)) NOT NULL,
    [AODISP23]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP23] DEFAULT ((-1)) NOT NULL,
    [AODISP24]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP24] DEFAULT ((-1)) NOT NULL,
    [AODISP25]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP25] DEFAULT ((-1)) NOT NULL,
    [AODISP26]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP26] DEFAULT ((-1)) NOT NULL,
    [AODISP27]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP27] DEFAULT ((-1)) NOT NULL,
    [AODISP28]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP28] DEFAULT ((-1)) NOT NULL,
    [AODISP29]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP29] DEFAULT ((-1)) NOT NULL,
    [AODISP30]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP30] DEFAULT ((-1)) NOT NULL,
    [AODISP31]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP31] DEFAULT ((-1)) NOT NULL,
    [AODISP32]   SMALLINT      CONSTRAINT [DF_AOPSTAT_AODISP32] DEFAULT ((-1)) NOT NULL,
    [AOOPSTATE]  SMALLINT      CONSTRAINT [DF_AOPSTAT_AOOPSTATE] DEFAULT ((0)) NOT NULL,
    [AOLOCK]     SMALLINT      CONSTRAINT [DF_AOPSTAT_AOLOCK] DEFAULT ((0)) NOT NULL,
    [AOHELP]     VARCHAR (100) CONSTRAINT [DF_AOPSTAT_AOHELP] DEFAULT ('') NOT NULL,
    [AOLIMIT]    SMALLINT      CONSTRAINT [DF_AOPSTAT_AOLIMIT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AOPSTAT] PRIMARY KEY CLUSTERED ([AOIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AOPSTAT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AOPSTAT';

