CREATE TABLE [dbo].[APROD] (
    [APIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [APDATE]    DATETIME NULL,
    [APWHO]     BIGINT   CONSTRAINT [DF_APROD_APWHO] DEFAULT ((0)) NOT NULL,
    [APAUIDENT] BIGINT   NOT NULL,
    [APPBIDENT] BIGINT   CONSTRAINT [DF_APROD_APPBIDENT] DEFAULT ((0)) NOT NULL,
    [APINTERN]  INT      CONSTRAINT [DF_APROD_APINTERN] DEFAULT ((0)) NOT NULL,
    [APSTIDENT] BIGINT   CONSTRAINT [DF_APROD_APSTIDENT] DEFAULT ((0)) NOT NULL,
    [APTANK]    TINYINT  CONSTRAINT [DF_APROD_APTANK] DEFAULT ((0)) NOT NULL,
    [APPROBE]   TINYINT  CONSTRAINT [DF_APROD_APPROBE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_APROD] PRIMARY KEY CLUSTERED ([APIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APROD';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'APROD';

