CREATE TABLE [dbo].[ASVSPEC] (
    [ASIDENT]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [ASDATE]     DATETIME      NULL,
    [ASWHO]      BIGINT        CONSTRAINT [DF_ASVSPEC_ASWHO] DEFAULT ((0)) NOT NULL,
    [ASAUIDENT]  BIGINT        CONSTRAINT [DF_ASVSPEC_ASAUIDENT] DEFAULT ((0)) NOT NULL,
    [ASCNT]      INT           CONSTRAINT [DF_ASVSPEC_ASCNT] DEFAULT ((0)) NOT NULL,
    [ASBLACK]    INT           CONSTRAINT [DF_ASVSPEC_ASBLACK] DEFAULT ((0)) NOT NULL,
    [ASREFERS]   INT           CONSTRAINT [DF_ASVSPEC_ASREFERS] DEFAULT ((0)) NOT NULL,
    [ASCHECK]    TINYINT       CONSTRAINT [DF_ASVSPEC_ASCHECK] DEFAULT ((0)) NOT NULL,
    [ASCANCEL]   TINYINT       CONSTRAINT [DF_ASVSPEC_ASCANCEL] DEFAULT ((0)) NOT NULL,
    [ASATTEND]   TINYINT       CONSTRAINT [DF_ASVSPEC_ASATTEND] DEFAULT ((0)) NOT NULL,
    [ASSMALL]    INT           CONSTRAINT [DF_ASVSPEC_ASSMALL] DEFAULT ((0)) NOT NULL,
    [ASBIG]      INT           CONSTRAINT [DF_ASVSPEC_ASBIG] DEFAULT ((0)) NOT NULL,
    [ASPREV]     TINYINT       CONSTRAINT [DF_ASVSPEC_ASPREV] DEFAULT ((0)) NOT NULL,
    [ASSYS]      BIGINT        CONSTRAINT [DF_ASVSPEC_ASSYS] DEFAULT ((0)) NOT NULL,
    [AS202]      TINYINT       CONSTRAINT [DF_ASVSPEC_AS202] DEFAULT ((0)) NOT NULL,
    [ASCARD]     TINYINT       CONSTRAINT [DF_ASVSPEC_ASCARD] DEFAULT ((0)) NOT NULL,
    [ASPRICE]    TINYINT       CONSTRAINT [DF_ASVSPEC_ASPRICE] DEFAULT ((0)) NOT NULL,
    [ASREF]      TINYINT       CONSTRAINT [DF_ASVSPEC_ASREF] DEFAULT ((0)) NOT NULL,
    [ASSTART]    INT           CONSTRAINT [DF_ASVSPEC_ASSTART] DEFAULT ((0)) NOT NULL,
    [ASEND]      INT           CONSTRAINT [DF_ASVSPEC_ASEND] DEFAULT ((0)) NOT NULL,
    [AS18]       TINYINT       CONSTRAINT [DF_ASVSPEC_AS18] DEFAULT ((0)) NOT NULL,
    [ASADDINPUT] TINYINT       CONSTRAINT [DF_ASVSPEC_ASADDINPUT] DEFAULT ((0)) NOT NULL,
    [ASTPRICE]   TINYINT       CONSTRAINT [DF_ASVSPEC_ASTPRICE] DEFAULT ((0)) NOT NULL,
    [ASTINTERN]  TINYINT       CONSTRAINT [DF_ASVSPEC_ASTINTERN] DEFAULT ((0)) NOT NULL,
    [ASPIN]      TINYINT       CONSTRAINT [DF_ASVSPEC_ASPIN] DEFAULT ((0)) NOT NULL,
    [ASLPIN]     TINYINT       CONSTRAINT [DF_ASVSPEC_ASLPIN] DEFAULT ((0)) NOT NULL,
    [ASIMP]      TINYINT       CONSTRAINT [DF_ASVSPEC_ASIMP] DEFAULT ((0)) NOT NULL,
    [ASMULDISP]  TINYINT       CONSTRAINT [DF_ASVSPEC_ASMULDISP] DEFAULT ((0)) NOT NULL,
    [ASDELAY]    TINYINT       CONSTRAINT [DF_ASVSPEC_ASDELAY] DEFAULT ((0)) NOT NULL,
    [ASVAIDENT1] BIGINT        CONSTRAINT [DF_ASVSPEC_ASVAIDENT1] DEFAULT ((0)) NOT NULL,
    [ASVAIDENT2] BIGINT        CONSTRAINT [DF_ASVSPEC_ASVAIDENT2] DEFAULT ((0)) NOT NULL,
    [AS306]      TINYINT       CONSTRAINT [DF_ASVSPEC_AS306] DEFAULT ((0)) NOT NULL,
    [ASCAL]      TINYINT       CONSTRAINT [DF_ASVSPEC_ASCAL] DEFAULT ((0)) NOT NULL,
    [AS042]      TINYINT       CONSTRAINT [DF_ASVSPEC_AS042] DEFAULT ((0)) NOT NULL,
    [AS043]      TINYINT       CONSTRAINT [DF_ASVSPEC_AS043] DEFAULT ((0)) NOT NULL,
    [ASINOUT]    TINYINT       CONSTRAINT [DF_ASVSPEC_ASINOUT] DEFAULT ((0)) NOT NULL,
    [AS2MEMO]    TINYINT       CONSTRAINT [DF_ASVSPEC_AS2MEMO] DEFAULT ((0)) NOT NULL,
    [ASOFFSET]   VARCHAR (MAX) CONSTRAINT [DF_ASVSPEC_ASOFFSET] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ASVSPEC] PRIMARY KEY CLUSTERED ([ASIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASVSPEC';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ASVSPEC';

