CREATE TABLE [dbo].[AUTHORIZE] (
    [AHIDENT] BIGINT       IDENTITY (1, 1) NOT NULL,
    [AHDATE]  DATETIME     CONSTRAINT [DF_AUTHORIZE_AHDATE] DEFAULT (getdate()) NULL,
    [AHWHO]   BIGINT       CONSTRAINT [DF_AUTHORIZE_AHWHO] DEFAULT ((0)) NOT NULL,
    [AHTITLE] VARCHAR (50) CONSTRAINT [DF_AUTHORIZE_AHTITLE] DEFAULT ('') NOT NULL,
    [AHPG1]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG1] DEFAULT ((0)) NOT NULL,
    [AHPG2]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG2] DEFAULT ((0)) NOT NULL,
    [AHPG3]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG3] DEFAULT ((0)) NOT NULL,
    [AHPG4]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG4] DEFAULT ((0)) NOT NULL,
    [AHPG5]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG5] DEFAULT ((0)) NOT NULL,
    [AHPG6]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG6] DEFAULT ((0)) NOT NULL,
    [AHPG7]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG7] DEFAULT ((0)) NOT NULL,
    [AHPG8]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG8] DEFAULT ((0)) NOT NULL,
    [AHPG9]   INT          CONSTRAINT [DF_AUTHORIZE_AHPG9] DEFAULT ((0)) NOT NULL,
    [AHPG10]  INT          CONSTRAINT [DF_AUTHORIZE_AHPG10] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AUTHORIZE] PRIMARY KEY CLUSTERED ([AHIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AUTHORIZE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AUTHORIZE';

