CREATE TABLE [dbo].[AUTOMAT] (
    [AUIDENT]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [AUDATE]           DATETIME      CONSTRAINT [DF_AUTOMAT_AUDATE] DEFAULT (getdate()) NULL,
    [AUWHO]            BIGINT        CONSTRAINT [DF_AUTOMAT_AUWHO] DEFAULT ((0)) NOT NULL,
    [AUNUMBER]         VARCHAR (20)  CONSTRAINT [DF_AUTOMAT_AUNUMBER] DEFAULT ('') NOT NULL,
    [AUTITLE]          VARCHAR (50)  CONSTRAINT [DF_AUTOMAT_AUTITLE] DEFAULT ('') NOT NULL,
    [AURELEASE]        INT           CONSTRAINT [DF_AUTOMAT_AURELEASE] DEFAULT ((0)) NOT NULL,
    [AURELSUB]         INT           CONSTRAINT [DF_AUTOMAT_AURELSUB] DEFAULT ((0)) NOT NULL,
    [AUAGIDENT]        BIGINT        CONSTRAINT [DF_AUTOMAT_AUAGIDENT] DEFAULT ((0)) NOT NULL,
    [AUFUIDENT]        BIGINT        CONSTRAINT [DF_AUTOMAT_AUFUIDENT] DEFAULT ((0)) NOT NULL,
    [AUTYPE]           TINYINT       CONSTRAINT [DF_AUTOMAT_AUTYPE] DEFAULT ((0)) NOT NULL,
    [AUAUTYPE]         TINYINT       CONSTRAINT [DF_AUTOMAT_AUAUTYPE] DEFAULT ((0)) NOT NULL,
    [AUMEMO]           VARCHAR (MAX) CONSTRAINT [DF_AUTOMAT_AUMEMO] DEFAULT ('') NOT NULL,
    [AUSYSNO]          VARCHAR (50)  CONSTRAINT [DF_AUTOMAT_AUSYSNO] DEFAULT ('') NOT NULL,
    [AUACTIVE]         TINYINT       CONSTRAINT [DF_AUTOMAT_AUACTIVE] DEFAULT ((0)) NOT NULL,
    [AUSERIES]         VARCHAR (20)  CONSTRAINT [DF_AUTOMAT_AUSERIES] DEFAULT ('') NOT NULL,
    [AUINTERN1]        VARCHAR (50)  CONSTRAINT [DF_AUTOMAT_AUINTERN1] DEFAULT ('') NOT NULL,
    [AUINTERN2]        VARCHAR (50)  CONSTRAINT [DF_AUTOMAT_AUINTERN2] DEFAULT ('') NOT NULL,
    [AUIFSFAIID]       BIGINT        CONSTRAINT [DF_AUTOMAT_AUIFSFAIID] DEFAULT ((0)) NOT NULL,
    [AUCASHREGISTERID] VARCHAR (50)  CONSTRAINT [DF_AUTOMAT_AUCASHREGISTERID] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_AUTOMAT] PRIMARY KEY CLUSTERED ([AUIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_AUTOMAT_WHO]
    ON [dbo].[AUTOMAT]([AUWHO] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_AUTOMAT_NAME]
    ON [dbo].[AUTOMAT]([AUTITLE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_AUTOMAT_NUMBER]
    ON [dbo].[AUTOMAT]([AUNUMBER] ASC) WHERE ([AUNUMBER]<>'');


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AUTOMAT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AUTOMAT';

