CREATE TABLE [dbo].[AWPLAN] (
    [AWIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [AWDATE]    DATETIME CONSTRAINT [DF_AWPLAN_AWDATE] DEFAULT (getdate()) NULL,
    [AWWHO]     BIGINT   CONSTRAINT [DF_AWPLAN_AWWHO] DEFAULT ((0)) NOT NULL,
    [AWAUIDENT] BIGINT   CONSTRAINT [DF_AWPLAN_AWAUIDENT] DEFAULT ((0)) NOT NULL,
    [AWMON]     TINYINT  CONSTRAINT [DF_AWPLAN_AWMON] DEFAULT ((0)) NOT NULL,
    [AWTUE]     TINYINT  CONSTRAINT [DF_AWPLAN_AWTUE] DEFAULT ((0)) NOT NULL,
    [AWWED]     TINYINT  CONSTRAINT [DF_AWPLAN_AWWED] DEFAULT ((0)) NOT NULL,
    [AWTHU]     TINYINT  CONSTRAINT [DF_AWPLAN_AWTHU] DEFAULT ((0)) NOT NULL,
    [AWFRI]     TINYINT  CONSTRAINT [DF_AWPLAN_AWFRI] DEFAULT ((0)) NOT NULL,
    [AWSAT]     TINYINT  CONSTRAINT [DF_AWPLAN_AWSAT] DEFAULT ((0)) NOT NULL,
    [AWSUN]     TINYINT  CONSTRAINT [DF_AWPLAN_AWSUN] DEFAULT ((0)) NOT NULL,
    [AWSTART]   SMALLINT CONSTRAINT [DF_AWPLAN_AWSTART] DEFAULT ((0)) NOT NULL,
    [AWEND]     SMALLINT CONSTRAINT [DF_AWPLAN_AWEND] DEFAULT ((0)) NOT NULL,
    [AWCYCLE]   INT      CONSTRAINT [DF_AWPLAN_AWCYCLE] DEFAULT ((0)) NOT NULL,
    [AWDAT01]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT01] DEFAULT ((0)) NOT NULL,
    [AWDAT02]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT02] DEFAULT ((0)) NOT NULL,
    [AWDAT03]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT03] DEFAULT ((0)) NOT NULL,
    [AWDAT04]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT04] DEFAULT ((0)) NOT NULL,
    [AWDAT05]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT05] DEFAULT ((0)) NOT NULL,
    [AWDAT06]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT06] DEFAULT ((0)) NOT NULL,
    [AWDAT07]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT07] DEFAULT ((0)) NOT NULL,
    [AWDAT08]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT08] DEFAULT ((0)) NOT NULL,
    [AWDAT09]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT09] DEFAULT ((0)) NOT NULL,
    [AWDAT10]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT10] DEFAULT ((0)) NOT NULL,
    [AWDAT11]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT11] DEFAULT ((0)) NOT NULL,
    [AWDAT12]   SMALLINT CONSTRAINT [DF_AWPLAN_AWDAT12] DEFAULT ((0)) NOT NULL,
    [AWDELAY]   TINYINT  CONSTRAINT [DF_AWPLAN_AWDELAY] DEFAULT ((0)) NOT NULL,
    [AWSTOCK]   TINYINT  CONSTRAINT [DF_AWPLAN_AWSTOCK] DEFAULT ((0)) NOT NULL,
    [AWPREPAID] TINYINT  CONSTRAINT [DF_AWPLAN_AWPREPAID] DEFAULT ((0)) NOT NULL,
    [AWJOURNAL] TINYINT  CONSTRAINT [DF_AWPLAN_AWJOURNAL] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AWPLAN] PRIMARY KEY CLUSTERED ([AWIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AWPLAN';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'AWPLAN';

