CREATE TABLE [dbo].[CAHISTORY] (
    [CHIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [CHDATE]    DATETIME CONSTRAINT [DF_CAHISTORY_CHDATE] DEFAULT (getdate()) NULL,
    [CHWHO]     BIGINT   CONSTRAINT [DF_CAHISTORY_CHWHO] DEFAULT ((0)) NOT NULL,
    [CHCAIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHCAIDENT] DEFAULT ((0)) NOT NULL,
    [CHLEIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHLEIDENT] DEFAULT ((0)) NOT NULL,
    [CHCOIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHCOIDENT] DEFAULT ((0)) NOT NULL,
    [CHVEIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHVEIDENT] DEFAULT ((0)) NOT NULL,
    [CHEMIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHEMIDENT] DEFAULT ((0)) NOT NULL,
    [CHFCIDENT] BIGINT   CONSTRAINT [DF_CAHISTORY_CHFCIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CAHISTORY] PRIMARY KEY CLUSTERED ([CHIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_CAHISTORY_CARD]
    ON [dbo].[CAHISTORY]([CHCAIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CAHISTORY_CARDDATE]
    ON [dbo].[CAHISTORY]([CHCAIDENT] ASC, [CHDATE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CAHISTORY';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CAHISTORY';

