CREATE TABLE [dbo].[CARDS] (
    [CAIDENT]   BIGINT       IDENTITY (1, 1) NOT NULL,
    [CADATE]    DATETIME     CONSTRAINT [DF_CARDS_CADATE] DEFAULT (getdate()) NULL,
    [CAWHO]     BIGINT       CONSTRAINT [DF_CARDS_CAWHO] DEFAULT ((0)) NOT NULL,
    [CANO]      VARCHAR (50) CONSTRAINT [DF_CARDS_CANO] DEFAULT ('') NOT NULL,
    [CANO2]     VARCHAR (50) CONSTRAINT [DF_CARDS_CANO2] DEFAULT ('') NOT NULL,
    [CATYPE]    TINYINT      CONSTRAINT [DF_CARDS_CATYPE] DEFAULT ((0)) NOT NULL,
    [CALEIDENT] BIGINT       CONSTRAINT [DF_CARDS_CALEIDENT] DEFAULT ((0)) NOT NULL,
    [CACOIDENT] BIGINT       CONSTRAINT [DF_CARDS_CACOIDENT] DEFAULT ((0)) NOT NULL,
    [CAVEIDENT] BIGINT       CONSTRAINT [DF_CARDS_CAVEIDENT] DEFAULT ((0)) NOT NULL,
    [CAEMIDENT] BIGINT       CONSTRAINT [DF_CARDS_CAEMIDENT] DEFAULT ((0)) NOT NULL,
    [CAFCIDENT] BIGINT       CONSTRAINT [DF_CARDS_CAFCIDENT] DEFAULT ((0)) NOT NULL,
    [CASTIDENT] BIGINT       CONSTRAINT [DF_CARDS_CASTIDENT] DEFAULT ((0)) NOT NULL,
    [CAPUIDENT] BIGINT       CONSTRAINT [DF_CARDS_CAPUIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CARDS] PRIMARY KEY CLUSTERED ([CAIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CAFCIDENT]
    ON [dbo].[CARDS]([CAFCIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CACOIDENT]
    ON [dbo].[CARDS]([CACOIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CANO]
    ON [dbo].[CARDS]([CANO] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CAEMIDENT]
    ON [dbo].[CARDS]([CAEMIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CAVEIDENT]
    ON [dbo].[CARDS]([CAVEIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CARDS_CATYPE]
    ON [dbo].[CARDS]([CATYPE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CARDS';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CARDS';

