CREATE TABLE [dbo].[CASHDISC] (
    [CIIDENT]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [CIWHO]    BIGINT         CONSTRAINT [DF_CASHDISC_CIWHO] DEFAULT ((0)) NOT NULL,
    [CIDATE]   DATETIME       NULL,
    [CITITLE1] VARCHAR (30)   CONSTRAINT [DF_CASHDISC_CITITLE1] DEFAULT ('1') NOT NULL,
    [CIVALUE1] NUMERIC (6, 2) CONSTRAINT [DF_CASHDISC_CIVALUE1] DEFAULT ((0)) NOT NULL,
    [CITITLE2] VARCHAR (30)   CONSTRAINT [DF_CASHDISC_CITITLE2] DEFAULT ('2') NOT NULL,
    [CIVALUE2] NUMERIC (6, 2) CONSTRAINT [DF_CASHDISC_CIVALUE2] DEFAULT ((0)) NOT NULL,
    [CITITLE3] VARCHAR (30)   CONSTRAINT [DF_CASHDISC_CITITLE3] DEFAULT ('3') NOT NULL,
    [CIVALUE3] NUMERIC (6, 2) CONSTRAINT [DF_CASHDISC_CIVALUE3] DEFAULT ((0)) NOT NULL,
    [CITITLE4] VARCHAR (30)   CONSTRAINT [DF_CASHDISC_CITITLE4] DEFAULT ('4') NOT NULL,
    [CIVALUE4] NUMERIC (6, 2) CONSTRAINT [DF_CASHDISC_CIVALUE4] DEFAULT ((0)) NOT NULL,
    [CITITLE5] VARCHAR (30)   CONSTRAINT [DF_CASHDISC_CITITLE5] DEFAULT ('5') NOT NULL,
    [CIVALUE5] NUMERIC (6, 2) CONSTRAINT [DF_CASHDISC_CIVALUE5] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CASHDISC] PRIMARY KEY CLUSTERED ([CIIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASHDISC';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASHDISC';

