CREATE TABLE [dbo].[CASH] (
    [CSIDENT]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [CSWHO]     BIGINT          NOT NULL,
    [CSDATE]    DATETIME        NULL,
    [CSPRIDENT] BIGINT          NULL,
    [CSQUANT]   NUMERIC (10, 3) CONSTRAINT [DF_CASH_CSQUANT] DEFAULT ((0)) NOT NULL,
    [CSPRICE]   NUMERIC (10, 2) CONSTRAINT [DF_CASH_CSPRICE] DEFAULT ((0)) NOT NULL,
    [CSLPRICE]  NUMERIC (10, 3) CONSTRAINT [DF_CASH_CSLPRICE] DEFAULT ((0)) NOT NULL,
    [CSCATYPE]  INT             CONSTRAINT [DF_CASH_CSCATYPE] DEFAULT ((0)) NOT NULL,
    [CSRECN1]   INT             CONSTRAINT [DF_CASH_CSRECN1] DEFAULT ((0)) NOT NULL,
    [CSRECN2]   INT             CONSTRAINT [DF_CASH_CSRECN2] DEFAULT ((0)) NOT NULL,
    [CSPROTNO]  INT             CONSTRAINT [DF_CASH_CSPROTNO] DEFAULT ((0)) NOT NULL,
    [CSAIIDENT] BIGINT          CONSTRAINT [DF_CASH_CSAIIDENT] DEFAULT ((0)) NOT NULL,
    [CSAUIDENT] BIGINT          CONSTRAINT [DF_CASH_CSAUIDENT] DEFAULT ((0)) NOT NULL,
    [CSSTIDENT] BIGINT          CONSTRAINT [DF_CASH_CSSTIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CASH] PRIMARY KEY CLUSTERED ([CSIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASH';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CASH';

