CREATE TABLE [dbo].[CRANGE] (
    [CRIDENT]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [CRWHO]    BIGINT        CONSTRAINT [DF_CRANGE_CRWHO] DEFAULT ((0)) NOT NULL,
    [CRDATE]   DATETIME      CONSTRAINT [DF_CRANGE_CRDATE] DEFAULT (getdate()) NOT NULL,
    [CRTITLE]  VARCHAR (50)  CONSTRAINT [DF_CRANGE_CRTITLE] DEFAULT ('') NOT NULL,
    [CRNUMBER] INT           CONSTRAINT [DF_CRANGE_CRNUMBER] DEFAULT ((0)) NOT NULL,
    [CRTYPE]   INT           CONSTRAINT [DF_CRANGE_CRTYPE] DEFAULT ((0)) NOT NULL,
    [CRMAXVAL] INT           CONSTRAINT [DF_CRANGE_CRMAXVAL] DEFAULT ((0)) NOT NULL,
    [CRMINVAL] INT           CONSTRAINT [DF_CRANGE_CRMINVAL] DEFAULT ((0)) NOT NULL,
    [CRCORR]   INT           CONSTRAINT [DF_CRANGE_CRCORR] DEFAULT ((0)) NOT NULL,
    [CRREP]    INT           CONSTRAINT [DF_CRANGE_CRREP] DEFAULT ((0)) NOT NULL,
    [CRMEMO]   VARCHAR (MAX) CONSTRAINT [DF_CRANGE_CRMEMO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CRANGE] PRIMARY KEY CLUSTERED ([CRIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CRANGE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'CRANGE';

