CREATE TABLE [dbo].[DISCPROD] (
    [DPIDENT]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [DPDATE]    DATETIME        CONSTRAINT [DF_DISCPROD_DPDATE] DEFAULT (getdate()) NULL,
    [DPWHO]     BIGINT          CONSTRAINT [DF_DISCPROD_DPWHO] DEFAULT ((0)) NOT NULL,
    [DPDIIDENT] BIGINT          CONSTRAINT [DF_DISCPROD_DPDIIDENT] DEFAULT ((0)) NOT NULL,
    [DPPBIDENT] BIGINT          CONSTRAINT [DF_DISCPROD_DPPBIDENT] DEFAULT ((0)) NOT NULL,
    [DPTYPE]    INT             CONSTRAINT [DF_DISCPROD_DPTYPE] DEFAULT ((0)) NOT NULL,
    [DPVALTYPE] INT             CONSTRAINT [DF_DISCPROD_DPVALTYPE] DEFAULT ((0)) NOT NULL,
    [DPQUANT]   DECIMAL (10, 3) CONSTRAINT [DF_DISCPROD_DPQUANT] DEFAULT ((0)) NOT NULL,
    [DPVALUE]   DECIMAL (10, 3) CONSTRAINT [DF_DISCPROD_DPVALUE] DEFAULT ((0)) NOT NULL,
    [DPVALDAT]  DATETIME        CONSTRAINT [DF_DISCPROD_DPVALDAT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_DISCPROD] PRIMARY KEY CLUSTERED ([DPIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DISCPROD';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'DISCPROD';

