CREATE TABLE [dbo].[EMPLOYEE] (
    [EMIDENT]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [EMDATE]     DATETIME      NULL,
    [EMWHO]      BIGINT        CONSTRAINT [DF_EMPLOYEE_EMWHO] DEFAULT ((0)) NOT NULL,
    [EMPERSNO]   VARCHAR (25)  CONSTRAINT [DF_EMPLOYEE_EMPERSNO] DEFAULT ('') NOT NULL,
    [EMDRIVNO]   VARCHAR (32)  CONSTRAINT [DF_EMPLOYEE_EMDRIVNO] DEFAULT ('') NOT NULL,
    [EMSTART]    DATETIME      NULL,
    [EMEND]      DATETIME      NULL,
    [EMTYPE]     TINYINT       CONSTRAINT [DF_EMPLOYEE_EMTYPE] DEFAULT ((0)) NOT NULL,
    [EMLEIDENT]  BIGINT        CONSTRAINT [DF_EMPLOYEE_EMLEIDENT] DEFAULT ((0)) NOT NULL,
    [EMCOIDENT]  BIGINT        CONSTRAINT [DF_EMPLOYEE_EMCOIDENT] DEFAULT ((0)) NOT NULL,
    [EMADIDENT]  BIGINT        CONSTRAINT [DF_EMPLOYEE_EMADIDENT] DEFAULT ((0)) NOT NULL,
    [EMMEMO]     VARCHAR (MAX) CONSTRAINT [DF_EMPLOYEE_EMMEMO] DEFAULT ('') NOT NULL,
    [EMSTATE]    VARCHAR (MAX) CONSTRAINT [DF_EMPLOYEE_EMSTATE] DEFAULT ('') NOT NULL,
    [EMADCOMP]   BIGINT        CONSTRAINT [DF_EMPLOYEE_EMADCOMP] DEFAULT ((0)) NOT NULL,
    [EMISCUST]   TINYINT       CONSTRAINT [DF_EMPLOYEE_EMISCUST] DEFAULT ((0)) NOT NULL,
    [EMCOID]     BIGINT        NULL,
    [EMCOCODE]   VARCHAR (50)  CONSTRAINT [DF_EMPLOYEE_EMCOCODE] DEFAULT ('') NOT NULL,
    [EMHO]       VARCHAR (50)  CONSTRAINT [DF_EMPLOYEE_EMHO] DEFAULT ('') NOT NULL,
    [EMDIVISION] VARCHAR (50)  CONSTRAINT [DF_EMPLOYEE_EMDIVISION] DEFAULT ('') NOT NULL,
    [EMDIVABBR]  VARCHAR (50)  CONSTRAINT [DF_EMPLOYEE_EMDIVABBR] DEFAULT ('') NOT NULL,
    [EMGROUP]    VARCHAR (50)  CONSTRAINT [DF_EMPLOYEE_EMGROUP] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED ([EMIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_EMPLOYEE_WHO]
    ON [dbo].[EMPLOYEE]([EMWHO] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_EMPLOYEE_PERSNO]
    ON [dbo].[EMPLOYEE]([EMPERSNO] ASC) WHERE ([EMPERSNO]<>'');


GO
CREATE NONCLUSTERED INDEX [INDEX_EMPLOYEE_DRIVNO]
    ON [dbo].[EMPLOYEE]([EMDRIVNO] ASC) WHERE ([EMDRIVNO]<>'');


GO
CREATE NONCLUSTERED INDEX [INDEX_EMPLOYEE_EMCOIDENT]
    ON [dbo].[EMPLOYEE]([EMCOIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_EMPLOYEE_EMCOID]
    ON [dbo].[EMPLOYEE]([EMCOID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMPLOYEE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EMPLOYEE';

