CREATE TABLE [dbo].[EVENT] (
    [EVIDENT]    BIGINT         IDENTITY (1, 1) NOT NULL,
    [EVWHO]      BIGINT         CONSTRAINT [DF_EVENT_EVWHO] DEFAULT ((0)) NOT NULL,
    [EVDATE]     DATETIME       CONSTRAINT [DF_EVENT_EVDATE] DEFAULT (getdate()) NULL,
    [EVSTART]    DATETIME       CONSTRAINT [DF_EVENT_EVSTART] DEFAULT (getdate()) NOT NULL,
    [EVEND]      DATETIME       CONSTRAINT [DF_EVENT_EVEND] DEFAULT (getdate()) NOT NULL,
    [EVSUBJECT]  VARCHAR (50)   CONSTRAINT [DF_EVENT_EVSUBJECT] DEFAULT ('') NOT NULL,
    [EVSTATE]    INT            CONSTRAINT [DF_EVENT_EVSTATE] DEFAULT ((0)) NOT NULL,
    [EVDESCR]    VARCHAR (MAX)  CONSTRAINT [DF_EVENT_EVDESCR] DEFAULT ('') NOT NULL,
    [EVLABEL]    INT            CONSTRAINT [DF_EVENT_EVLABEL] DEFAULT ((0)) NOT NULL,
    [EVLABELID]  BIGINT         CONSTRAINT [DF_EVENT_EVLABELID] DEFAULT ((0)) NOT NULL,
    [EVLOCATION] VARCHAR (50)   CONSTRAINT [DF_EVENT_EVLOCATION] DEFAULT ('') NOT NULL,
    [EVALLDAY]   TINYINT        CONSTRAINT [DF_EVENT_EVALLDAY] DEFAULT ((0)) NOT NULL,
    [EVEVTYPE]   INT            CONSTRAINT [DF_EVENT_EVEVTYPE] DEFAULT ((0)) NOT NULL,
    [EVRECURR]   VARCHAR (MAX)  CONSTRAINT [DF_EVENT_EVRECURR] DEFAULT ('') NOT NULL,
    [EVREMIND]   VARCHAR (MAX)  CONSTRAINT [DF_EVENT_EVREMIND] DEFAULT ('') NOT NULL,
    [EVVEIDENT]  BIGINT         CONSTRAINT [DF_EVENT_EVVEIDENT] DEFAULT ((0)) NOT NULL,
    [EVEMIDENT]  BIGINT         CONSTRAINT [DF_EVENT_EVEMIDENT] DEFAULT ((0)) NOT NULL,
    [EVDONE]     VARCHAR (MAX)  CONSTRAINT [DF_EVENT_EVDONE] DEFAULT ((0)) NOT NULL,
    [EVDONEDATE] DATETIME       CONSTRAINT [DF_EVENT_EVDONEDATE] DEFAULT (getdate()) NOT NULL,
    [EVEMID]     BIGINT         CONSTRAINT [DF_EVENT_EVEMID] DEFAULT ((0)) NOT NULL,
    [EVCONFIRM]  INT            CONSTRAINT [DF_EVENT_EVCONFIRM] DEFAULT ((0)) NOT NULL,
    [EVDAYS]     INT            CONSTRAINT [DF_EVENT_EVDAYS] DEFAULT ((0)) NOT NULL,
    [EVMILES]    INT            CONSTRAINT [DF_EVENT_EVMILES] DEFAULT ((0)) NOT NULL,
    [EVOFFMILES] INT            CONSTRAINT [DF_EVENT_EVOFFMILES] DEFAULT ((0)) NOT NULL,
    [EVHOURS]    DECIMAL (8, 2) CONSTRAINT [DF_EVENT_EVHOURS] DEFAULT ((0)) NOT NULL,
    [EVOFFHOURS] DECIMAL (8, 2) CONSTRAINT [DF_EVENT_EVOFFHOURS] DEFAULT ((0)) NOT NULL,
    [EVTYPE]     INT            CONSTRAINT [DF_EVENT_EVTYPE] DEFAULT ((0)) NOT NULL,
    [EVHRECURR]  DECIMAL (8, 2) CONSTRAINT [DF_EVENT_EVHRECURR] DEFAULT ((0)) NOT NULL,
    [EVHDONE]    DECIMAL (8, 2) CONSTRAINT [DF_EVENT_EVHDONE] DEFAULT ((0)) NOT NULL,
    [EVMRECURR]  INT            CONSTRAINT [DF_EVENT_EVMRECURR] DEFAULT ((0)) NOT NULL,
    [EVMDONE]    INT            CONSTRAINT [DF_EVENT_EVMDONE] DEFAULT ((0)) NOT NULL,
    [EVRECTYPE]  INT            CONSTRAINT [DF_EVENT_EVRECTYPE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED ([EVIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_EVENT_EVENT]
    ON [dbo].[EVENT]([EVSTART] ASC, [EVEND] ASC, [EVVEIDENT] ASC, [EVDONEDATE] ASC)
    INCLUDE([EVIDENT], [EVSUBJECT], [EVLOCATION], [EVDAYS], [EVMILES], [EVOFFMILES], [EVHOURS], [EVOFFHOURS], [EVTYPE], [EVHDONE], [EVMDONE]);


GO
CREATE NONCLUSTERED INDEX [INDEX_EVENT_VEHICLE]
    ON [dbo].[EVENT]([EVVEIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_EVENT_EMIDENT]
    ON [dbo].[EVENT]([EVEMIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EVENT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EVENT';

