CREATE TABLE [dbo].[GLBSEARCH] (
    [GLIDENT] BIGINT     IDENTITY (1, 1) NOT NULL,
    [GLDATE]  DATETIME   NULL,
    [GLWHO]   BIGINT     CONSTRAINT [DF_GLBSEARCH_GLWHO] DEFAULT ((0)) NOT NULL,
    [GLSCOPE] INT        CONSTRAINT [DF_GLBSEARCH_GLSCOPE] DEFAULT ((0)) NOT NULL,
    [GLSQL]   CHAR (400) CONSTRAINT [DF_GLBSEARCH_GLSQL] DEFAULT ('') NOT NULL,
    [GLTEXT]  CHAR (100) CONSTRAINT [DF_GLBSEARCH_GLTEXT] DEFAULT ('') NOT NULL,
    [GLFIELD] CHAR (50)  CONSTRAINT [DF_GLBSEARCH_GLFIELD] DEFAULT ('') NOT NULL,
    [GLITEM]  CHAR (50)  CONSTRAINT [DF_GLBSEARCH_GLITEM] DEFAULT ('') NOT NULL,
    [GLPROG]  TINYINT    CONSTRAINT [DF_GLBSEARCH_GLPROG] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_GLBSEARCH] PRIMARY KEY CLUSTERED ([GLIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GLBSEARCH';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'GLBSEARCH';

