CREATE TABLE [dbo].[INVCHARGE] (
    [ICIDENT]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [ICWHO]     BIGINT         CONSTRAINT [DF_INVCHARGE_ICWHO] DEFAULT ((0)) NOT NULL,
    [ICDATE]    DATETIME       NULL,
    [ICTITLE1]  VARCHAR (30)   CONSTRAINT [DF_INVCHARGE_ICTITLE1] DEFAULT ('1') NOT NULL,
    [ICVALUE1]  NUMERIC (6, 2) CONSTRAINT [DF_INVCHARGE_ICVALUE1] DEFAULT ((0)) NOT NULL,
    [ICTITLE2]  VARCHAR (30)   CONSTRAINT [DF_INVCHARGE_ICTITLE2] DEFAULT ('2') NOT NULL,
    [ICVALUE2]  NUMERIC (6, 2) CONSTRAINT [DF_INVCHARGE_ICVALUE2] DEFAULT ((0)) NOT NULL,
    [ICTITLE3]  VARCHAR (30)   CONSTRAINT [DF_INVCHARGE_ICTITLE3] DEFAULT ('3') NOT NULL,
    [ICVALUE3]  NUMERIC (6, 2) CONSTRAINT [DF_INVCHARGE_ICVALUE3] DEFAULT ((0)) NOT NULL,
    [ICTITLE4]  VARCHAR (30)   CONSTRAINT [DF_INVCHARGE_ICTITLE4] DEFAULT ('4') NOT NULL,
    [ICVALUE4]  NUMERIC (6, 2) CONSTRAINT [DF_INVCHARGE_ICVALUE4] DEFAULT ((0)) NOT NULL,
    [ICTITLE5]  VARCHAR (30)   CONSTRAINT [DF_INVCHARGE_ICTITLE5] DEFAULT ('5') NOT NULL,
    [ICVALUE5]  NUMERIC (6, 2) CONSTRAINT [DF_INVCHARGE_ICVALUE5] DEFAULT ((0)) NOT NULL,
    [ICPBIDENT] BIGINT         CONSTRAINT [DF_INVCHARGE_ICPBIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_INVCHARGE] PRIMARY KEY CLUSTERED ([ICIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVCHARGE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVCHARGE';

