CREATE TABLE [dbo].[INVENTORY] (
    [INIDENT]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [INDATE]      DATETIME        NULL,
    [INWHO]       BIGINT          CONSTRAINT [DF_INVENTORY_INWHO] DEFAULT ((0)) NOT NULL,
    [INSTIDENT]   BIGINT          CONSTRAINT [DF_INVENTORY_INSTIDENT] DEFAULT ((0)) NOT NULL,
    [ININDATE]    DATETIME        NULL,
    [INQUANT]     NUMERIC (12, 3) CONSTRAINT [DF_INVENTORY_INQUANT] DEFAULT ((0)) NOT NULL,
    [INPBIDENT]   BIGINT          CONSTRAINT [DF_INVENTORY_INPBIDENT] DEFAULT ((0)) NOT NULL,
    [INACT]       NUMERIC (12, 3) CONSTRAINT [DF_INVENTORY_INACT] DEFAULT ((0)) NOT NULL,
    [INBUYPRICE]  NUMERIC (10, 4) CONSTRAINT [DF_INVENTORY_INBUYPRICE] DEFAULT ((0)) NOT NULL,
    [INSELLPRICE] NUMERIC (10, 4) CONSTRAINT [DF_INVENTORY_INSELLPRICE] DEFAULT ((0)) NOT NULL,
    [INWBP]       NUMERIC (10, 4) CONSTRAINT [DF_INVENTORY_INWBP] DEFAULT ((0)) NOT NULL,
    [INNEWWBP]    NUMERIC (10, 4) CONSTRAINT [DF_INVENTORY_INNEWWBP] DEFAULT ((0)) NOT NULL,
    [INCOIDENT]   BIGINT          CONSTRAINT [DF_INVENTORY_INCOIDENT] DEFAULT ((0)) NOT NULL,
    [INCORR]      TINYINT         CONSTRAINT [DF_INVENTORY_INCORR] DEFAULT ((0)) NOT NULL,
    [INMEMO]      VARCHAR (MAX)   CONSTRAINT [DF_INVENTORY_INMEMO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_INVENTORY] PRIMARY KEY CLUSTERED ([INIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_ININDATE]
    ON [dbo].[INVENTORY]([ININDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_ININDATE1]
    ON [dbo].[INVENTORY]([ININDATE] DESC);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_INPBIDENT]
    ON [dbo].[INVENTORY]([INPBIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_INCOIDENT]
    ON [dbo].[INVENTORY]([INCOIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_INSTIDENT]
    ON [dbo].[INVENTORY]([INSTIDENT] ASC, [ININDATE] ASC)
    INCLUDE([INWBP], [INNEWWBP], [INCORR]);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_INQUANT]
    ON [dbo].[INVENTORY]([INQUANT] ASC, [INNEWWBP] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_INVENTORY_INSTIDENT1]
    ON [dbo].[INVENTORY]([INSTIDENT] ASC, [INPBIDENT] ASC, [ININDATE] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVENTORY';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVENTORY';

