CREATE TABLE [dbo].[INVINV] (
    [IIIDENT]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [IIWHO]     BIGINT          CONSTRAINT [DF_INVINV_IIWHO] DEFAULT ((0)) NOT NULL,
    [IIDATE]    DATETIME        CONSTRAINT [DF_INVINV_IIDATE] DEFAULT (getdate()) NOT NULL,
    [IIGROSS]   NUMERIC (12, 2) CONSTRAINT [DF_INVINV_IIGROSS] DEFAULT ((0)) NOT NULL,
    [IINET]     NUMERIC (12, 2) CONSTRAINT [DF_INVINV_IINET] DEFAULT ((0)) NOT NULL,
    [IIDISC]    NUMERIC (12, 2) CONSTRAINT [DF_INVINV_IIDISC] DEFAULT ((0)) NOT NULL,
    [IIVAT]     NUMERIC (12, 2) CONSTRAINT [DF_INVINV_IIVAT] DEFAULT ((0)) NOT NULL,
    [IICNT]     INT             CONSTRAINT [DF_INVINV_IICNT] DEFAULT ((0)) NOT NULL,
    [IIDTADATE] DATETIME        NULL,
    [IIBDISK]   INT             CONSTRAINT [DF_INVINV_IIBDISK] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_INVINV] PRIMARY KEY CLUSTERED ([IIIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVINV';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVINV';

