CREATE TABLE [dbo].[INVITEM] (
    [ITIDENT]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [ITIVIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITIVIDENT] DEFAULT ((0)) NOT NULL,
    [ITRECTYPE]   INT             CONSTRAINT [DF_INVITEM_ITRECTYPE] DEFAULT ((0)) NOT NULL,
    [ITCURRNO]    INT             CONSTRAINT [DF_INVITEM_ITCURRNO] DEFAULT ((0)) NOT NULL,
    [ITIDATE]     DATETIME        CONSTRAINT [DF_INVITEM_ITIDATE] DEFAULT (getdate()) NULL,
    [ITNAME]      VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITNAME] DEFAULT ('') NOT NULL,
    [ITEMIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITEMIDENT] DEFAULT ((0)) NOT NULL,
    [ITPLATE]     VARCHAR (20)    CONSTRAINT [DF_INVITEM_ITPLATE] DEFAULT ('') NOT NULL,
    [ITINTNO]     VARCHAR (40)    CONSTRAINT [DF_INVITEM_ITINTNO] DEFAULT ('') NOT NULL,
    [ITVEIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITVEIDENT] DEFAULT ((0)) NOT NULL,
    [ITVECC]      VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITVECC] DEFAULT ('') NOT NULL,
    [ITVESTOC]    VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITVESTOC] DEFAULT ('') NOT NULL,
    [ITMILES]     INT             CONSTRAINT [DF_INVITEM_ITMILES] DEFAULT ((0)) NOT NULL,
    [ITHOURS]     DECIMAL (10, 2) CONSTRAINT [DF_INVITEM_ITHOURS] DEFAULT ((0)) NOT NULL,
    [ITPROD]      VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITPROD] DEFAULT ('') NOT NULL,
    [ITPRODNUM]   VARCHAR (20)    CONSTRAINT [DF_INVITEM_ITPRODNUM] DEFAULT ('') NOT NULL,
    [ITPBIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITPBIDENT] DEFAULT ((0)) NOT NULL,
    [ITQUANT]     DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITQUANT] DEFAULT ((0)) NOT NULL,
    [ITUSPPRICE]  DECIMAL (12, 4) CONSTRAINT [DF_INVITEM_ITUSPPRICE] DEFAULT ((0)) NOT NULL,
    [ITUSPPRICEN] DECIMAL (12, 4) CONSTRAINT [DF_INVITEM_ITUSPPRICEN] DEFAULT ((0)) NOT NULL,
    [ITUPPPRICEG] DECIMAL (12, 4) CONSTRAINT [DF_INVITEM_ITUPPPRICEG] DEFAULT ((0)) NOT NULL,
    [ITUPPPRICE]  DECIMAL (12, 4) CONSTRAINT [DF_INVITEM_ITUPPPRICE] DEFAULT ((0)) NOT NULL,
    [ITSPTOTALN]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITSPTOTALN] DEFAULT ((0)) NOT NULL,
    [ITSPTOTALG]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITSPTOTALG] DEFAULT ((0)) NOT NULL,
    [ITPPTOTALN]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITPPTOTALN] DEFAULT ((0)) NOT NULL,
    [ITPPTOTALG]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITPPTOTALG] DEFAULT ((0)) NOT NULL,
    [ITINVPBASE]  INT             CONSTRAINT [DF_INVITEM_ITINVPBASE] DEFAULT ((0)) NOT NULL,
    [ITINVPRICE]  DECIMAL (12, 4) CONSTRAINT [DF_INVITEM_ITINVPRICE] DEFAULT ((0)) NOT NULL,
    [ITINVTOTAL]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITINVTOTAL] DEFAULT ((0)) NOT NULL,
    [ITVAT]       DECIMAL (4, 2)  CONSTRAINT [DF_INVITEM_ITVAT] DEFAULT ((0)) NOT NULL,
    [ITSPVATVAL]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITSPVATVAL] DEFAULT ((0)) NOT NULL,
    [ITPPVATVAL]  DECIMAL (12, 2) CONSTRAINT [DF_INVITEM_ITPPVATVAL] DEFAULT ((0)) NOT NULL,
    [ITCANO1]     VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITCANO1] DEFAULT ('') NOT NULL,
    [ITCAIDENT1]  BIGINT          CONSTRAINT [DF_INVITEM_ITCAIDENT1] DEFAULT ((0)) NOT NULL,
    [ITCANO2]     VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITCANO2] DEFAULT ('') NOT NULL,
    [ITCAIDENT2]  BIGINT          CONSTRAINT [DF_INVITEM_ITCAIDENT2] DEFAULT ((0)) NOT NULL,
    [ITFUSTAT]    VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITFUSTAT] DEFAULT ('') NOT NULL,
    [ITFUIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITFUIDENT] DEFAULT ((0)) NOT NULL,
    [ITHIIDENT]   BIGINT          CONSTRAINT [DF_INVITEM_ITHIIDENT] DEFAULT ((0)) NOT NULL,
    [ITVEHCANO]   VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITVEHCANO] DEFAULT ('') NOT NULL,
    [ITPERSCANO]  VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITPERSCANO] DEFAULT ('') NOT NULL,
    [ITHIINFO]    BIGINT          CONSTRAINT [DF_INVITEM_ITHIINFO] DEFAULT ((0)) NOT NULL,
    [ITIPNUMBER]  VARCHAR (30)    CONSTRAINT [DF_INVITEM_ITIPNUMBER] DEFAULT ('') NOT NULL,
    [ITIPTITLE]   VARCHAR (50)    CONSTRAINT [DF_INVITEM_ITIPTITLE] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_INVITEM] PRIMARY KEY CLUSTERED ([ITIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVITEM';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVITEM';

