CREATE TABLE [dbo].[INVNUM] (
    [IUIDENT]   BIGINT       IDENTITY (1, 1) NOT NULL,
    [IUWHO]     BIGINT       CONSTRAINT [DF_INVNUM_IUWHO] DEFAULT ((0)) NOT NULL,
    [IUDATE]    DATETIME     CONSTRAINT [DF_INVNUM_IUDATE] DEFAULT (getdate()) NULL,
    [IUCURR]    INT          CONSTRAINT [DF_INVNUM_IUCURR] DEFAULT ((0)) NOT NULL,
    [IULENGTH]  INT          CONSTRAINT [DF_INVNUM_IULENGTH] DEFAULT ((0)) NOT NULL,
    [IUTYPE]    INT          CONSTRAINT [DF_INVNUM_IUTYPE] DEFAULT ((0)) NOT NULL,
    [IUVALUE]   VARCHAR (20) CONSTRAINT [DF_INVNUM_IUVALUE] DEFAULT ('') NOT NULL,
    [IUCNT]     BIGINT       CONSTRAINT [DF_INVNUM_IUCNT] DEFAULT ((0)) NOT NULL,
    [IUSTART]   BIGINT       CONSTRAINT [DF_INVNUM_IUSTART] DEFAULT ((1)) NOT NULL,
    [IUINC]     INT          CONSTRAINT [DF_INVNUM_IUINC] DEFAULT ((1)) NOT NULL,
    [IURESDATE] DATETIME     CONSTRAINT [DF_INVNUM_IURESDATE] DEFAULT (getdate()) NOT NULL,
    [IUFILLER]  INT          CONSTRAINT [DF_INVNUM_IUFILLER] DEFAULT ((0)) NOT NULL,
    [IUNOTYPE]  INT          CONSTRAINT [DF_INVNUM_IUNOTYPE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_INVNUM] PRIMARY KEY CLUSTERED ([IUIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVNUM';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'INVNUM';

