CREATE TABLE [dbo].[LEVELMETER] (
    [LMIDENT]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [LMDATE]      DATETIME      CONSTRAINT [DF_LEVELMETER_LMDATE] DEFAULT (getdate()) NULL,
    [LMWHO]       BIGINT        CONSTRAINT [DF_LEVELMETER_LMWHO] DEFAULT ((0)) NOT NULL,
    [LMTITLE]     VARCHAR (150) NOT NULL,
    [LMNUMBER]    VARCHAR (20)  CONSTRAINT [DF_LEVELMETER_LMNUMBER] DEFAULT ('') NOT NULL,
    [LMAUIDENT]   BIGINT        NOT NULL,
    [LMFORMAT]    INT           NOT NULL,
    [LMSTIDENT01] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT01] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT02] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT02] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT03] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT03] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT04] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT04] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT05] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT05] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT06] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT06] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT07] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT07] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT08] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT08] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT09] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT09] DEFAULT ((0)) NOT NULL,
    [LMSTIDENT10] BIGINT        CONSTRAINT [DF_LEVELMETER_LMSTIDENT10] DEFAULT ((0)) NOT NULL,
    [LMPOS01]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS01] DEFAULT ((0)) NOT NULL,
    [LMPOS02]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS02] DEFAULT ((0)) NOT NULL,
    [LMPOS03]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS03] DEFAULT ((0)) NOT NULL,
    [LMPOS04]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS04] DEFAULT ((0)) NOT NULL,
    [LMPOS05]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS05] DEFAULT ((0)) NOT NULL,
    [LMPOS06]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS06] DEFAULT ((0)) NOT NULL,
    [LMPOS07]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS07] DEFAULT ((0)) NOT NULL,
    [LMPOS08]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS08] DEFAULT ((0)) NOT NULL,
    [LMPOS09]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS09] DEFAULT ((0)) NOT NULL,
    [LMPOS10]     INT           CONSTRAINT [DF_LEVELMETER_LMPOS10] DEFAULT ((0)) NOT NULL,
    [LMBAUD]      INT           CONSTRAINT [DF_LEVELMETER_LMBAUD] DEFAULT ((1200)) NOT NULL,
    [LMPORT]      INT           CONSTRAINT [DF_LEVELMETER_LMPORT] DEFAULT ((0)) NOT NULL,
    [LMACTIVE]    INT           CONSTRAINT [DF_LEVELMETER_LMACTIVE] DEFAULT ((0)) NOT NULL,
    [LMPROTTYPE]  INT           CONSTRAINT [DF_LEVELMETER_LMPROTTYPE] DEFAULT ((1)) NOT NULL,
    [LMHEIGHT]    INT           CONSTRAINT [DF_LEVELMETER_LMHEIGHT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_LEVELMETER] PRIMARY KEY CLUSTERED ([LMIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LEVELMETER';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'LEVELMETER';

