CREATE TABLE [dbo].[NSCSPEC] (
    [NSIDENT]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [NSDATE]      DATETIME      CONSTRAINT [DF_NSCSPEC_NSDATE] DEFAULT (getdate()) NOT NULL,
    [NSWHO]       BIGINT        NOT NULL,
    [NSAUIDENT]   BIGINT        CONSTRAINT [DF_NSCSPEC_NSAUIDENT] DEFAULT ((0)) NOT NULL,
    [NSCALSUM]    VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSCALSUM] DEFAULT ('') NOT NULL,
    [NSCALDATE]   DATETIME      NULL,
    [NSCALSTR]    VARCHAR (MAX) CONSTRAINT [DF_NSCSPEC_NSCALSTR] DEFAULT ('') NOT NULL,
    [NSHWSTR]     VARCHAR (MAX) CONSTRAINT [DF_NSCSPEC_NSHWSTR] DEFAULT ('') NOT NULL,
    [NSTPRICE]    INT           CONSTRAINT [DF_NSCSPEC_NSTPRICE] DEFAULT ((0)) NOT NULL,
    [NSTINTERN]   INT           CONSTRAINT [DF_NSCSPEC_NSTINTERN] DEFAULT ((0)) NOT NULL,
    [NSDIAL1]     VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSDIAL1] DEFAULT ('') NOT NULL,
    [NSDIAL2]     VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSDIAL2] DEFAULT ('') NOT NULL,
    [NSDIAL3]     VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSDIAL3] DEFAULT ('') NOT NULL,
    [NSDIAL4]     VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSDIAL4] DEFAULT ('') NOT NULL,
    [NSDIAL5]     VARCHAR (50)  CONSTRAINT [DF_NSCSPEC_NSDIAL5] DEFAULT ('') NOT NULL,
    [NSTYPE1]     INT           CONSTRAINT [DF_NSCSPEC_NSTYPE1] DEFAULT ((0)) NOT NULL,
    [NSTYPE2]     INT           CONSTRAINT [DF_NSCSPEC_NSTYPE2] DEFAULT ((0)) NOT NULL,
    [NSTYPE3]     INT           CONSTRAINT [DF_NSCSPEC_NSTYPE3] DEFAULT ((0)) NOT NULL,
    [NSTYPE4]     INT           CONSTRAINT [DF_NSCSPEC_NSTYPE4] DEFAULT ((0)) NOT NULL,
    [NSTYPE5]     INT           CONSTRAINT [DF_NSCSPEC_NSTYPE5] DEFAULT ((0)) NOT NULL,
    [NSCLOCKTIME] INT           CONSTRAINT [DF_NSCSPEC_NSCLOCKTIME] DEFAULT ((0)) NOT NULL,
    [NSNOCHANGE]  INT           CONSTRAINT [DF_NSCSPEC_NSNOCHANGE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_NSCSPEC] PRIMARY KEY CLUSTERED ([NSIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NSCSPEC';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NSCSPEC';

