CREATE TABLE [dbo].[NSCSTAT] (
    [NTIDENT]    BIGINT   IDENTITY (1, 1) NOT NULL,
    [NTDATE]     DATETIME CONSTRAINT [DF_NSCSTAT_NTDATE] DEFAULT (getdate()) NOT NULL,
    [NTWHO]      BIGINT   CONSTRAINT [DF_NSCSTAT_NTWHO] DEFAULT ((0)) NOT NULL,
    [NTAUIDENT]  BIGINT   NOT NULL,
    [NTTRNUM]    INT      CONSTRAINT [DF_NSCSTAT_NTTRNUM] DEFAULT ((0)) NOT NULL,
    [NTTANUM]    INT      CONSTRAINT [DF_NSCSTAT_NTTANUM] DEFAULT ((0)) NOT NULL,
    [NTRECNO]    INT      CONSTRAINT [DF_NSCSTAT_NTRECNO] DEFAULT ((0)) NOT NULL,
    [NTBNWRECNO] INT      CONSTRAINT [DF_NSCSTAT_NTBNWRECNO] DEFAULT ((0)) NOT NULL,
    [NTNSCBL]    INT      CONSTRAINT [DF_NSCSTAT_NTNSCBL] DEFAULT ((0)) NOT NULL,
    [NTPCBL]     INT      CONSTRAINT [DF_NSCSTAT_NTPCBL] DEFAULT ((0)) NOT NULL,
    [NTEJNUM]    INT      CONSTRAINT [DF_NSCSTAT_NTEJNUM] DEFAULT ((0)) NOT NULL,
    [NTEJDATE]   DATETIME NULL,
    [NTRESPBL]   INT      CONSTRAINT [DF_NSCSTAT_NTRESPBL] DEFAULT ((0)) NOT NULL,
    [NTRESPNUM]  INT      CONSTRAINT [DF_NSCSTAT_NTRESPNUM] DEFAULT ((0)) NOT NULL,
    [NTTRSTAT]   INT      CONSTRAINT [DF_NSCSTAT_NTTRSTAT] DEFAULT ((0)) NOT NULL,
    [NTNSCSTAT]  INT      CONSTRAINT [DF_NSCSTAT_NTNSCSTAT] DEFAULT ((0)) NOT NULL,
    [NTNSCERR]   INT      CONSTRAINT [DF_NSCSTAT_NTNSCERR] DEFAULT ((0)) NOT NULL,
    [NTEJSTAT]   INT      CONSTRAINT [DF_NSCSTAT_NTEJSTAT] DEFAULT ((0)) NOT NULL,
    [NTLASTBLNO] INT      CONSTRAINT [DF_NSCSTAT_NTLASTBLNO] DEFAULT ((0)) NOT NULL,
    [NTSTARTGAP] INT      CONSTRAINT [DF_NSCSTAT_NTSTARTGAP] DEFAULT ((0)) NOT NULL,
    [NTENDGAP]   INT      CONSTRAINT [DF_NSCSTAT_NTENDGAP] DEFAULT ((0)) NOT NULL,
    [NTTERM]     INT      CONSTRAINT [DF_NSCSTAT_NTTERM] DEFAULT ((0)) NOT NULL,
    [NTNOZZLE]   INT      CONSTRAINT [DF_NSCSTAT_NTNOZZLE] DEFAULT ((0)) NOT NULL,
    [NTTERM1S]   INT      CONSTRAINT [DF_NSCSTAT_NTTERM1S] DEFAULT ((0)) NOT NULL,
    [NTTERM1E]   INT      CONSTRAINT [DF_NSCSTAT_NTTERM1E] DEFAULT ((0)) NOT NULL,
    [NTTERM1RPS] INT      CONSTRAINT [DF_NSCSTAT_NTTERM1RPS] DEFAULT ((0)) NOT NULL,
    [NTTERM1RPE] INT      CONSTRAINT [DF_NSCSTAT_NTTERM1RPE] DEFAULT ((0)) NOT NULL,
    [NTTERM2S]   INT      CONSTRAINT [DF_NSCSTAT_NTTERM2S] DEFAULT ((0)) NOT NULL,
    [NTTERM2E]   INT      CONSTRAINT [DF_NSCSTAT_NTTERM2E] DEFAULT ((0)) NOT NULL,
    [NTTERM2RPS] INT      CONSTRAINT [DF_NSCSTAT_NTTERM2RPS] DEFAULT ((0)) NOT NULL,
    [NTTERM2RPE] INT      CONSTRAINT [DF_NSCSTAT_NTTERM2RPE] DEFAULT ((0)) NOT NULL,
    [NTRRSTAT]   INT      CONSTRAINT [DF_NSCSTAT_NTRRSTAT] DEFAULT ((0)) NOT NULL,
    [NTRRDATE]   DATETIME NULL,
    CONSTRAINT [PK_NSCSTAT] PRIMARY KEY CLUSTERED ([NTIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NSCSTAT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'NSCSTAT';

