CREATE TABLE [dbo].[ORDERS] (
    [ORIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [ORDATE]    DATETIME      CONSTRAINT [DF_ORDERS_ORDATE] DEFAULT (getdate()) NULL,
    [ORAUIDENT] BIGINT        CONSTRAINT [DF_ORDERS_ORAUIDENT] DEFAULT ((0)) NOT NULL,
    [ORSTATE]   TINYINT       CONSTRAINT [DF_ORDERS_ORSTATE] DEFAULT ((0)) NOT NULL,
    [ORRQNO]    BIGINT        CONSTRAINT [DF_ORDERS_ORRQNO] DEFAULT ((0)) NOT NULL,
    [ORDATA]    VARCHAR (100) CONSTRAINT [DF_ORDERS_ORDATA] DEFAULT ('') NOT NULL,
    [ORERROR]   INT           CONSTRAINT [DF_ORDERS_ORERROR] DEFAULT ((0)) NOT NULL,
    [ORPROGNO]  INT           CONSTRAINT [DF_ORDERS_ORPROGNO] DEFAULT ((0)) NOT NULL,
    [ORCNT]     INT           CONSTRAINT [DF_ORDERS_ORCNT] DEFAULT ((0)) NOT NULL,
    [ORWHO]     BIGINT        NULL,
    [ORSTART]   DATETIME      NULL,
    CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED ([ORIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_ORDERS_STATE]
    ON [dbo].[ORDERS]([ORSTATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_ORDERS_TERMINAL]
    ON [dbo].[ORDERS]([ORAUIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ORDERS';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ORDERS';

