CREATE TABLE [dbo].[OVERVIEWS] (
    [OVIDENT]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [OVDATE]       DATETIME     NULL,
    [OVUSIDENT]    BIGINT       CONSTRAINT [DF_OVERVIEWS_OVUSIDENT] DEFAULT ((0)) NOT NULL,
    [OVNUM]        INT          CONSTRAINT [DF_OVERVIEWS_OVNUM] DEFAULT ((0)) NOT NULL,
    [OVCOLNUM]     INT          CONSTRAINT [DF_OVERVIEWS_OVCOLNUM] DEFAULT ((0)) NOT NULL,
    [OVCOLTITLE]   VARCHAR (20) CONSTRAINT [DF_OVERVIEWS_OVCOLTITLE] DEFAULT ('') NOT NULL,
    [OVCOLUSTITLE] VARCHAR (50) CONSTRAINT [DF_OVERVIEWS_OVCOLUSTITLE] DEFAULT ('') NOT NULL,
    [OVCOLSIZE]    INT          CONSTRAINT [DF_OVERVIEWS_OVCOLSIZE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OVERVIEWS] PRIMARY KEY CLUSTERED ([OVIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OVERVIEWS';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OVERVIEWS';

