CREATE TABLE [dbo].[OVSORT] (
    [OSIDENT]   BIGINT       IDENTITY (1, 1) NOT NULL,
    [OSDATE]    DATETIME     NULL,
    [OSUSIDENT] BIGINT       CONSTRAINT [DF_OVSORT_OSUSIDENT] DEFAULT ((0)) NOT NULL,
    [OSOVNUM]   INT          CONSTRAINT [DF_OVSORT_OSOVNUM] DEFAULT ((0)) NOT NULL,
    [OSTITLE]   VARCHAR (50) CONSTRAINT [DF_OVSORT_OSTITLE] DEFAULT ('') NOT NULL,
    [OSSORT1]   VARCHAR (15) CONSTRAINT [DF_OVSORT_OSSORT1] DEFAULT ('') NOT NULL,
    [OSSORT2]   VARCHAR (15) CONSTRAINT [DF_OVSORT_OSSORT2] DEFAULT ('') NOT NULL,
    [OSSORT3]   VARCHAR (15) CONSTRAINT [DF_OVSORT_OSSORT3] DEFAULT ('') NOT NULL,
    [OSSORT4]   VARCHAR (15) CONSTRAINT [DF_OVSORT_OSSORT4] DEFAULT ('') NOT NULL,
    [OSSORT5]   VARCHAR (15) CONSTRAINT [DF_OVSORT_OSSORT5] DEFAULT ('') NOT NULL,
    [OSFILTER]  INT          CONSTRAINT [DF_OVSORT_OSFILTER] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OVSORT] PRIMARY KEY CLUSTERED ([OSIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OVSORT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'OVSORT';

