CREATE TABLE [dbo].[PBASE] (
    [PBIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [PBDATE]    DATETIME      CONSTRAINT [DF_PBASE_PBDATE] DEFAULT (getdate()) NULL,
    [PBWHO]     BIGINT        CONSTRAINT [DF_PBASE_PBWHO] DEFAULT ((0)) NOT NULL,
    [PBTITLE]   VARCHAR (50)  CONSTRAINT [DF_PBASE_PBTITLE] DEFAULT ('') NOT NULL,
    [PBNUMBER]  VARCHAR (20)  CONSTRAINT [DF_PBASE_PBNUMBER] DEFAULT ('') NOT NULL,
    [PBMEMO]    VARCHAR (MAX) CONSTRAINT [DF_PBASE_PBMEMO] DEFAULT ('') NOT NULL,
    [PBPGIDENT] BIGINT        CONSTRAINT [DF_PBASE_PBPGIDENT] DEFAULT ((0)) NOT NULL,
    [PBPTIDENT] BIGINT        CONSTRAINT [DF_PBASE_PBPTIDENT] DEFAULT ((0)) NOT NULL,
    [PBEXTERN]  VARCHAR (25)  CONSTRAINT [DF_PBASE_PBEXTERN] DEFAULT ('') NOT NULL,
    [PBEAN]     VARCHAR (15)  CONSTRAINT [DF_PBASE_PBEAN] DEFAULT ('') NOT NULL,
    [PBDISPL]   BIGINT        CONSTRAINT [DF_PBASE_PBDISPL] DEFAULT ((0)) NOT NULL,
    [PBVAIDENT] BIGINT        CONSTRAINT [DF_PBASE_PBVAIDENT] DEFAULT ((0)) NOT NULL,
    [PBTYPE]    INT           CONSTRAINT [DF_PBASE_PBTYPE] DEFAULT ((0)) NOT NULL,
    [PBIMPORT]  TINYINT       CONSTRAINT [DF_PBASE_PBIMPORT] DEFAULT ((0)) NOT NULL,
    [PBNSCNUM]  INT           CONSTRAINT [DF_PBASE_PBNSCNUM] DEFAULT ((0)) NOT NULL,
    [PBNSCRCPT] VARCHAR (10)  CONSTRAINT [DF_PBASE_PBNSCRCPT] DEFAULT ('') NOT NULL,
    [PBNSCONLT] VARCHAR (50)  CONSTRAINT [DF_PBASE_PBNSCONLT] DEFAULT ('') NOT NULL,
    [PBNSCONLN] VARCHAR (5)   CONSTRAINT [DF_PBASE_PBNSCONLN] DEFAULT ('') NOT NULL,
    [PBNSCPTF1] INT           CONSTRAINT [DF_PBASE_PBNSCPTF1] DEFAULT ((0)) NOT NULL,
    [PBNSCPTF2] INT           CONSTRAINT [DF_PBASE_PBNSCPTF2] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PBASE] PRIMARY KEY CLUSTERED ([PBIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_PBASE_WHO]
    ON [dbo].[PBASE]([PBWHO] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_PBASE_NAME]
    ON [dbo].[PBASE]([PBTITLE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_PBASE_NUMBER]
    ON [dbo].[PBASE]([PBNUMBER] ASC) WHERE ([PBNUMBER]<>'');


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PBASE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PBASE';

