CREATE TABLE [dbo].[PPRICE] (
    [PPIDENT]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [PPDATE]    DATETIME        NULL,
    [PPWHO]     BIGINT          CONSTRAINT [DF_PPRICE_PPWHO] DEFAULT ((0)) NOT NULL,
    [PPPBIDENT] BIGINT          CONSTRAINT [DF_PPRICE_PPPBIDENT] DEFAULT ((0)) NOT NULL,
    [PPTYPE]    TINYINT         CONSTRAINT [DF_PPRICE_PPTYPE] DEFAULT ((0)) NOT NULL,
    [PPPRICE]   DECIMAL (10, 4) CONSTRAINT [DF_PPRICE_PPPRICE] DEFAULT ((0)) NOT NULL,
    [PPEFFDATE] DATETIME        NULL,
    [PPVAT]     DECIMAL (6, 2)  CONSTRAINT [DF_PPRICE_PPVAT] DEFAULT ((0)) NOT NULL,
    [PPVAIDENT] BIGINT          CONSTRAINT [DF_PPRICE_PPVAIDENT] DEFAULT ((0)) NOT NULL,
    [PPFUIDENT] BIGINT          CONSTRAINT [DF_PPRICE_PPFUIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PPRICE] PRIMARY KEY CLUSTERED ([PPIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PPRICE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PPRICE';

