CREATE TABLE [dbo].[PREAUTH] (
    [PAIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [PADATE]    DATETIME CONSTRAINT [DF_PREAUTH_PADATE] DEFAULT (getdate()) NULL,
    [PAWHO]     BIGINT   CONSTRAINT [DF_PREAUTH_PAWHO] DEFAULT ((0)) NOT NULL,
    [PACARD]    INT      CONSTRAINT [DF_PREAUTH_PACARD] DEFAULT ((0)) NOT NULL,
    [PACAR]     INT      CONSTRAINT [DF_PREAUTH_PACAR] DEFAULT ((0)) NOT NULL,
    [PATRUCK]   INT      CONSTRAINT [DF_PREAUTH_PATRUCK] DEFAULT ((0)) NOT NULL,
    [PAAUIDENT] BIGINT   CONSTRAINT [DF_PREAUTH_PAAUIDENT] DEFAULT ((0)) NOT NULL,
    [PARECEIPT] INT      CONSTRAINT [DF_PREAUTH_PARECEIPT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PREAUTH] PRIMARY KEY CLUSTERED ([PAIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PREAUTH';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PREAUTH';

