CREATE TABLE [dbo].[PRICPROD] (
    [PIIDENT]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [PIDATE]    DATETIME        CONSTRAINT [DF_PRICPROD_PIDATE] DEFAULT (getdate()) NULL,
    [PIWHO]     BIGINT          CONSTRAINT [DF_PRICPROD_PIWHO] DEFAULT ((0)) NOT NULL,
    [PIPRIDENT] BIGINT          CONSTRAINT [DF_PRICPROD_PIPRIDENT] DEFAULT ((0)) NOT NULL,
    [PIPBIDENT] BIGINT          CONSTRAINT [DF_PRICPROD_PIPBIDENT] DEFAULT ((0)) NOT NULL,
    [PITYPE]    INT             CONSTRAINT [DF_PRICPROD_PITYPE] DEFAULT ((0)) NOT NULL,
    [PIVALTYPE] INT             CONSTRAINT [DF_PRICPROD_PIVALTYPE] DEFAULT ((0)) NOT NULL,
    [PIVALUE]   DECIMAL (10, 4) CONSTRAINT [DF_PRICPROD_PIVALUE] DEFAULT ((0)) NOT NULL,
    [PIVALDAT]  DATETIME        CONSTRAINT [DF_PRICPROD_PIVALDAT] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_PRICPROD] PRIMARY KEY CLUSTERED ([PIIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRICPROD';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PRICPROD';

