CREATE TABLE [dbo].[PTYPE] (
    [PTIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [PTDATE]    DATETIME      CONSTRAINT [DF_PTYPE_PTDATE] DEFAULT (getdate()) NULL,
    [PTWHO]     BIGINT        CONSTRAINT [DF_PTYPE_PTWHO] DEFAULT ((0)) NOT NULL,
    [PTTITLE]   VARCHAR (50)  CONSTRAINT [DF_PTYPE_PTTITLE] DEFAULT ('') NOT NULL,
    [PTNUMBER]  VARCHAR (20)  CONSTRAINT [DF_PTYPE_PTNUMBER] DEFAULT ('') NOT NULL,
    [PTMEMO]    VARCHAR (MAX) CONSTRAINT [DF_PTYPE_PTMEMO] DEFAULT ('') NOT NULL,
    [PTQUIDENT] BIGINT        CONSTRAINT [DF_PTYPE_PTQUIDENT] DEFAULT ((0)) NOT NULL,
    [PTTYPE]    INT           CONSTRAINT [DF_PTYPE_PTTYPE] DEFAULT ((0)) NOT NULL,
    [PTFLTYPE]  INT           CONSTRAINT [DF_PTYPE_PTFLTYPE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PTYPE] PRIMARY KEY CLUSTERED ([PTIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PTYPE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PTYPE';

