CREATE TABLE [dbo].[QUEUES] (
    [QEIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [QEDATE]    DATETIME      CONSTRAINT [DF_QUEUES_QEDATE] DEFAULT (getdate()) NULL,
    [QEORIDENT] BIGINT        CONSTRAINT [DF_QUEUES_QEORIDENT] DEFAULT ((0)) NOT NULL,
    [QEAUIDENT] BIGINT        CONSTRAINT [DF_QUEUES_QEAUIDENT] DEFAULT ((0)) NOT NULL,
    [QESTATE]   INT           CONSTRAINT [DF_QUEUES_QESTATE] DEFAULT ((1)) NOT NULL,
    [QERQNO]    BIGINT        CONSTRAINT [DF_QUEUES_QERQNO] DEFAULT ((0)) NOT NULL,
    [QEDATA]    VARCHAR (MAX) CONSTRAINT [DF_QUEUES_QEDATA] DEFAULT ('') NOT NULL,
    [QECNT]     INT           CONSTRAINT [DF_QUEUES_QECNT] DEFAULT ((0)) NOT NULL,
    [QEBLOCKNO] BIGINT        CONSTRAINT [DF_QUEUES_QEBLOCKNO] DEFAULT ((-1)) NOT NULL,
    CONSTRAINT [PK_QUEUES] PRIMARY KEY CLUSTERED ([QEIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_QUEUES_STATE]
    ON [dbo].[QUEUES]([QESTATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_QUEUES_TERMINAL]
    ON [dbo].[QUEUES]([QEAUIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_QUEUES_QEDATE]
    ON [dbo].[QUEUES]([QEDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_QUEUES_QEORIDENT]
    ON [dbo].[QUEUES]([QEORIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [NONCLUSTEREDINDEX-20160510-101016]
    ON [dbo].[QUEUES]([QESTATE] ASC)
    INCLUDE([QEAUIDENT]);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'QUEUES';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'QUEUES';

