CREATE TABLE [dbo].[REFERENCE] (
    [REIDENT]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [RECAIDENT]   BIGINT       CONSTRAINT [DF_REFERENCE_RECAIDENT] DEFAULT ((0)) NOT NULL,
    [REAUIDENT]   BIGINT       CONSTRAINT [DF_REFERENCE_REAUIDENT] DEFAULT ((0)) NOT NULL,
    [REDOWN]      TINYINT      CONSTRAINT [DF_REFERENCE_REDOWN] DEFAULT ((0)) NOT NULL,
    [REATT]       TINYINT      CONSTRAINT [DF_REFERENCE_REATT] DEFAULT ((0)) NOT NULL,
    [RETYPE]      TINYINT      CONSTRAINT [DF_REFERENCE_RETYPE] DEFAULT ((0)) NOT NULL,
    [RELOCK]      TINYINT      CONSTRAINT [DF_REFERENCE_RELOCK] DEFAULT ((0)) NOT NULL,
    [REPIN]       TINYINT      CONSTRAINT [DF_REFERENCE_REPIN] DEFAULT ((0)) NOT NULL,
    [RECODE]      INT          CONSTRAINT [DF_REFERENCE_RECODE] DEFAULT ((0)) NOT NULL,
    [RECODENSC]   VARCHAR (32) CONSTRAINT [DF_REFERENCE_RECODENSC] DEFAULT ('') NOT NULL,
    [REMILEAGE]   TINYINT      CONSTRAINT [DF_REFERENCE_REMILEAGE] DEFAULT ((0)) NOT NULL,
    [RERANGE]     TINYINT      CONSTRAINT [DF_REFERENCE_RERANGE] DEFAULT ((0)) NOT NULL,
    [READDIN]     TINYINT      CONSTRAINT [DF_REFERENCE_READDIN] DEFAULT ((0)) NOT NULL,
    [REAPIDENT]   BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT] DEFAULT ((0)) NOT NULL,
    [REAPIDENT2]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT2] DEFAULT ((0)) NOT NULL,
    [REAPIDENT3]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT3] DEFAULT ((0)) NOT NULL,
    [REAPIDENT4]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT4] DEFAULT ((0)) NOT NULL,
    [REAPIDENT5]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT5] DEFAULT ((0)) NOT NULL,
    [REAPIDENT6]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT6] DEFAULT ((0)) NOT NULL,
    [REAPIDENT7]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT7] DEFAULT ((0)) NOT NULL,
    [REAPIDENT8]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT8] DEFAULT ((0)) NOT NULL,
    [REAPIDENT9]  BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT9] DEFAULT ((0)) NOT NULL,
    [REAPIDENT10] BIGINT       CONSTRAINT [DF_REFERENCE_REAPIDENT10] DEFAULT ((0)) NOT NULL,
    [REAPGROUP]   INT          CONSTRAINT [DF_REFERENCE_REAPGROUP] DEFAULT ((0)) NOT NULL,
    [RELEX]       TINYINT      CONSTRAINT [DF_REFERENCE_RELEX] DEFAULT ((0)) NOT NULL,
    [RESECOND]    TINYINT      CONSTRAINT [DF_REFERENCE_RESECOND] DEFAULT ((0)) NOT NULL,
    [RELIMIT]     TINYINT      CONSTRAINT [DF_REFERENCE_RELIMIT] DEFAULT ((0)) NOT NULL,
    [REMESSNO]    TINYINT      CONSTRAINT [DF_REFERENCE_REMESSNO] DEFAULT ((0)) NOT NULL,
    [RECC]        INT          CONSTRAINT [DF_REFERENCE_RECC] DEFAULT ((0)) NOT NULL,
    [REOFFGROUP]  TINYINT      CONSTRAINT [DF_REFERENCE_REOFFGROUP] DEFAULT ((0)) NOT NULL,
    [REHH]        TINYINT      CONSTRAINT [DF_REFERENCE_REHH] DEFAULT ((0)) NOT NULL,
    [RECOLSTATE]  TINYINT      CONSTRAINT [DF_REFERENCE_RECOLSTATE] DEFAULT ((0)) NOT NULL,
    [REOGIDENT]   BIGINT       CONSTRAINT [DF_REFERENCE_REOGIDENT] DEFAULT ((0)) NOT NULL,
    [RECRIDENT]   BIGINT       CONSTRAINT [DF_REFERENCE_RECRIDENT] DEFAULT ((0)) NOT NULL,
    [REDIAL]      TINYINT      CONSTRAINT [DF_REFERENCE_REDIAL] DEFAULT ((0)) NOT NULL,
    [REPRIVATE]   TINYINT      CONSTRAINT [DF_REFERENCE_REPRIVATE] DEFAULT ((0)) NOT NULL,
    [REVALID]     DATETIME     NULL,
    [REEXPIRE]    DATETIME     NULL,
    [REQUANT]     INT          CONSTRAINT [DF_REFERENCE_REQUANT] DEFAULT ((0)) NOT NULL,
    [REDIALOG]    INT          CONSTRAINT [DF_REFERENCE_REDIALOG] DEFAULT ((0)) NOT NULL,
    [REPINONL]    VARCHAR (20) CONSTRAINT [DF_REFERENCE_REPINONL] DEFAULT ('') NULL,
    [REAUTOCNT]   INT          CONSTRAINT [DF_REFERENCE_REAUTOCNT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_REFERENCE] PRIMARY KEY CLUSTERED ([REIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_REFERENCE_RECAIDENT]
    ON [dbo].[REFERENCE]([RECAIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_REFERENCE_REAUIDENT]
    ON [dbo].[REFERENCE]([REAUIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'REFERENCE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'REFERENCE';

