CREATE TABLE [dbo].[RESPONSE] (
    [RSIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [RSDATE]    DATETIME      CONSTRAINT [DF_RESPONSE_RSDATE] DEFAULT (getdate()) NULL,
    [RSORIDENT] BIGINT        CONSTRAINT [DF_RESPONSE_RSORIDENT] DEFAULT ((0)) NOT NULL,
    [RSAUIDENT] BIGINT        CONSTRAINT [DF_RESPONSE_RSAUIDENT] DEFAULT ((0)) NOT NULL,
    [RSSTATE]   INT           CONSTRAINT [DF_RESPONSE_RSSTATE] DEFAULT ((0)) NOT NULL,
    [RSDATA]    VARCHAR (100) CONSTRAINT [DF_RESPONSE_RSDATA] DEFAULT ('') NOT NULL,
    [RSRQNO]    BIGINT        CONSTRAINT [DF_RESPONSE_RSRQNO] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_RESPONSE] PRIMARY KEY CLUSTERED ([RSIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RESPONSE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'RESPONSE';

