CREATE TABLE [dbo].[SCHARAC] (
    [SCIDENT]   BIGINT IDENTITY (1, 1) NOT NULL,
    [SCHIIDENT] BIGINT CONSTRAINT [DF_SCHARAC_SCHIIDENT] DEFAULT ((0)) NOT NULL,
    [SCVCIDENT] BIGINT CONSTRAINT [DF_SCHARAC_SCVCIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SCHARAC] PRIMARY KEY CLUSTERED ([SCIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_SCHARAC_SCHIIDENT]
    ON [dbo].[SCHARAC]([SCHIIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_SCHARAC_SCVCIDENT]
    ON [dbo].[SCHARAC]([SCVCIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SCHARAC';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SCHARAC';

