CREATE TABLE [dbo].[SEARCH] (
    [SEIDENT]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [SEDATE]     DATETIME      CONSTRAINT [DF_SEARCH_SEDATE] DEFAULT (getdate()) NULL,
    [SEWHO]      BIGINT        CONSTRAINT [DF_SEARCH_SEWHO] DEFAULT ((0)) NOT NULL,
    [SELISTTYPE] INT           CONSTRAINT [DF_SEARCH_SELISTTYPE] DEFAULT ((0)) NOT NULL,
    [SESQL]      VARCHAR (MAX) CONSTRAINT [DF_SEARCH_SESQL] DEFAULT ('') NOT NULL,
    [SECAP]      VARCHAR (30)  CONSTRAINT [DF_SEARCH_SECAP] DEFAULT ('') NOT NULL,
    [SEPROG]     TINYINT       CONSTRAINT [DF_SEARCH_SEPROG] DEFAULT ((0)) NOT NULL,
    [SEAUTO]     TINYINT       CONSTRAINT [DF_SEARCH_SEAUTO] DEFAULT ((0)) NOT NULL,
    [SEMEMO]     VARCHAR (MAX) CONSTRAINT [DF_SEARCH_SEMEMO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_SEARCH] PRIMARY KEY CLUSTERED ([SEIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SEARCH';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SEARCH';

