CREATE TABLE [dbo].[STHISTORY] (
    [SHIDENT]   BIGINT   IDENTITY (1, 1) NOT NULL,
    [SHDATE]    DATETIME CONSTRAINT [DF_STHISTORY_SHDATE] DEFAULT (getdate()) NULL,
    [SHWHO]     BIGINT   CONSTRAINT [DF_STHISTORY_SHWHO] DEFAULT ((0)) NOT NULL,
    [SHVALDATE] DATETIME CONSTRAINT [DF_STHISTORY_SHVALDATE] DEFAULT ('') NOT NULL,
    [SHSRIDENT] BIGINT   CONSTRAINT [DF_STHISTORY_SHSRIDENT] DEFAULT ('') NOT NULL,
    [SHCOIDENT] BIGINT   CONSTRAINT [DF_STHISTORY_SHCOIDENT] DEFAULT ('') NOT NULL,
    [SHVEIDENT] BIGINT   CONSTRAINT [DF_STHISTORY_SHVEIDENT] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_STHISTORY] PRIMARY KEY CLUSTERED ([SHIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_STHISTORY_SHCOIDENT]
    ON [dbo].[STHISTORY]([SHCOIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_STHISTORY_SHVALDATE]
    ON [dbo].[STHISTORY]([SHVALDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_STHISTORY_SHVEIDENT]
    ON [dbo].[STHISTORY]([SHVEIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_STHISTORY_SHSRIDENT]
    ON [dbo].[STHISTORY]([SHSRIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'STHISTORY';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'STHISTORY';

