CREATE TABLE [dbo].[SVACCOUNT] (
    [SVIDENT]   BIGINT IDENTITY (1, 1) NOT NULL,
    [SVCAIDENT] BIGINT CONSTRAINT [DF_SVACCOUNT_SVCAIDENT] DEFAULT ((0)) NOT NULL,
    [SVAUIDENT] BIGINT CONSTRAINT [DF_SVACCOUNT_SVAUIDENT] DEFAULT ((0)) NOT NULL,
    [SVACCOUNT] INT    CONSTRAINT [DF_SVACCOUNT_SVACCOUNT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SVACCOUNT] PRIMARY KEY CLUSTERED ([SVIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_SVACCOUNT_CARD]
    ON [dbo].[SVACCOUNT]([SVCAIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_SVACCOUNT_TERMINAL]
    ON [dbo].[SVACCOUNT]([SVAUIDENT] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_SVACCOUNT_CARDTERM]
    ON [dbo].[SVACCOUNT]([SVAUIDENT] ASC, [SVCAIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SVACCOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SVACCOUNT';

