CREATE TABLE [dbo].[SYSTEM] (
    [SYIDENT]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [SYDATE]      DATETIME      CONSTRAINT [DF_SYSTEM_SYDATE] DEFAULT (getdate()) NOT NULL,
    [SYWHO]       BIGINT        CONSTRAINT [DF_SYSTEM_SYWHO] DEFAULT ((0)) NOT NULL,
    [SYMAID]      INT           CONSTRAINT [DF_SYSTEM_SYMAID] DEFAULT ((6)) NOT NULL,
    [SYCNT]       INT           CONSTRAINT [DF_SYSTEM_SYCNT] DEFAULT ((1)) NOT NULL,
    [SYYEAR]      INT           CONSTRAINT [DF_SYSTEM_SYYEAR] DEFAULT (datepart(year,getdate())) NOT NULL,
    [SYIBANCHECK] INT           CONSTRAINT [DF_SYSTEM_SYIBANCHECK] DEFAULT ((1)) NOT NULL,
    [SYCTRYNO]    INT           CONSTRAINT [DF_SYSTEM_SYCTRYNO] DEFAULT ((0)) NOT NULL,
    [SYPAIN]      INT           CONSTRAINT [DF_SYSTEM_SYPAIN] DEFAULT ((2)) NOT NULL,
    [SYSENDSEPA]  INT           CONSTRAINT [DF_SYSTEM_SYSENDSEPA] DEFAULT ((1)) NOT NULL,
    [SYATTACHIN]  INT           CONSTRAINT [DF_SYSTEM_SYATTACHIN] DEFAULT ((1)) NOT NULL,
    [SYSEPA]      INT           CONSTRAINT [DF_SYSTEM_SYSEPA] DEFAULT ((1)) NOT NULL,
    [SYSMTP]      VARCHAR (100) CONSTRAINT [DF_SYSTEM_SYSMTP] DEFAULT ('') NOT NULL,
    [SYFROM]      VARCHAR (100) CONSTRAINT [DF_SYSTEM_SYFROM] DEFAULT ('') NOT NULL,
    [SYUSER]      VARCHAR (100) CONSTRAINT [DF_SYSTEM_SYUSER] DEFAULT ('') NOT NULL,
    [SYPW]        VARCHAR (100) CONSTRAINT [DF_SYSTEM_SYPW] DEFAULT ('') NOT NULL,
    [SYPORT]      INT           CONSTRAINT [DF_SYSTEM_SYPORT] DEFAULT ((0)) NOT NULL,
    [SYSSL]       INT           CONSTRAINT [DF_SYSTEM_SYSSL] DEFAULT ((0)) NOT NULL,
    [SYTEXT]      VARCHAR (140) CONSTRAINT [DF_SYSTEM_SYTEXT] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_SYSTEM] PRIMARY KEY CLUSTERED ([SYIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYSTEM';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'SYSTEM';

