CREATE TABLE [dbo].[VAT] (
    [VAIDENT]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [VADATE]   DATETIME       CONSTRAINT [DF_VAT_VADATE] DEFAULT (getdate()) NULL,
    [VAWHO]    BIGINT         CONSTRAINT [DF_VAT_VAWHO] DEFAULT ((0)) NOT NULL,
    [VAVAT]    NUMERIC (6, 2) CONSTRAINT [DF_VAT_VAVAT] DEFAULT ((0)) NOT NULL,
    [VAVATCHG] NUMERIC (6, 2) CONSTRAINT [DF_VAT_VAVATCHG] DEFAULT ((0)) NOT NULL,
    [VAVATDAT] DATETIME       CONSTRAINT [DF_VAT_VAVATDAT] DEFAULT (getdate()) NULL,
    [VATYPE]   TINYINT        CONSTRAINT [DF_VAT_VATYPE] DEFAULT ((0)) NOT NULL,
    [VANUMBER] VARCHAR (20)   CONSTRAINT [DF_VAT_VANUMBER] DEFAULT ('') NOT NULL,
    [VATITLE]  VARCHAR (50)   CONSTRAINT [DF_VAT_VATITLE] DEFAULT ('') NOT NULL,
    [VAMEMO]   VARCHAR (MAX)  CONSTRAINT [DF_VAT_VAMEMO] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_VAT] PRIMARY KEY CLUSTERED ([VAIDENT] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VAT';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VAT';

