CREATE TABLE [dbo].[VCHARAC] (
    [VCIDENT]   BIGINT        IDENTITY (1, 1) NOT NULL,
    [VCDATE]    DATETIME      CONSTRAINT [DF_VCHARAC_VCDATE] DEFAULT (getdate()) NULL,
    [VCWHO]     BIGINT        CONSTRAINT [DF_VCHARAC_VCWHO] DEFAULT ((0)) NOT NULL,
    [VCNUMBER]  VARCHAR (20)  CONSTRAINT [DF_VCHARAC_VCNUMBER] DEFAULT ('') NOT NULL,
    [VCTITLE]   VARCHAR (50)  CONSTRAINT [DF_VCHARAC_VCTITLE] DEFAULT ('') NOT NULL,
    [VCMEMO]    VARCHAR (MAX) CONSTRAINT [DF_VCHARAC_VCMEMO] DEFAULT ('') NOT NULL,
    [VCVFIDENT] BIGINT        CONSTRAINT [DF_VCHARAC_VCVFIDENT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_VCHARAC] PRIMARY KEY CLUSTERED ([VCIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_VCHARAC_VCVFIDENT]
    ON [dbo].[VCHARAC]([VCVFIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VCHARAC';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VCHARAC';

