CREATE TABLE [dbo].[VEHICLE] (
    [VEIDENT]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [VEDATE]     DATETIME        CONSTRAINT [DF_VEHICLE_VEDATE] DEFAULT (getdate()) NULL,
    [VEWHO]      BIGINT          CONSTRAINT [DF_VEHICLE_VEWHO] DEFAULT ((0)) NOT NULL,
    [VEINTNO]    VARCHAR (40)    CONSTRAINT [DF_VEHICLE_VEINTNO] DEFAULT ('') NOT NULL,
    [VEVEHNO]    VARCHAR (32)    CONSTRAINT [DF_VEHICLE_VEVEHNO] DEFAULT ('') NOT NULL,
    [VEPLATE]    VARCHAR (20)    CONSTRAINT [DF_VEHICLE_VEPLATE] DEFAULT ('') NOT NULL,
    [VEMEMO]     VARCHAR (MAX)   CONSTRAINT [DF_VEHICLE_VEMEMO] DEFAULT ('') NOT NULL,
    [VEPBIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VEPBIDENT] DEFAULT ((0)) NOT NULL,
    [VEPGIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VEPGIDENT] DEFAULT ((0)) NOT NULL,
    [VESTART]    DATETIME        CONSTRAINT [DF_VEHICLE_VESTART] DEFAULT (NULL) NULL,
    [VEEND]      DATETIME        NULL,
    [VELEIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VELEIDENT] DEFAULT ((0)) NOT NULL,
    [VECOIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VECOIDENT] DEFAULT ((0)) NOT NULL,
    [VECC]       VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VECC] DEFAULT ('') NOT NULL,
    [VEEMIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VEEMIDENT] DEFAULT ((0)) NOT NULL,
    [VESTOC]     VARCHAR (20)    CONSTRAINT [DF_VEHICLE_VESTOC] DEFAULT ('') NOT NULL,
    [VESRIDENT]  BIGINT          CONSTRAINT [DF_VEHICLE_VESRIDENT] DEFAULT ((0)) NOT NULL,
    [VEMILES]    INT             CONSTRAINT [DF_VEHICLE_VEMILES] DEFAULT ((0)) NOT NULL,
    [VEHOURS]    DECIMAL (10, 2) CONSTRAINT [DF_VEHICLE_VEHOURS] DEFAULT ((0)) NOT NULL,
    [VETYPE]     TINYINT         CONSTRAINT [DF_VEHICLE_VETYPE] DEFAULT ((0)) NOT NULL,
    [VEKMOFFSET] INT             CONSTRAINT [DF_VEHICLE_VEKMOFFSET] DEFAULT ((0)) NOT NULL,
    [VEHHOFFSET] DECIMAL (10, 2) CONSTRAINT [DF_VEHICLE_VEHHOFFSET] DEFAULT ((0)) NOT NULL,
    [VEOFFDATE]  DATETIME        NULL,
    [VEKMSTART]  INT             CONSTRAINT [DF_VEHICLE_VEKMSTART] DEFAULT ((0)) NOT NULL,
    [VEHHSTART]  DECIMAL (10, 2) CONSTRAINT [DF_VEHICLE_VEHHSTART] DEFAULT ((0)) NOT NULL,
    [VEPLATE2]   VARCHAR (20)    CONSTRAINT [DF_VEHICLE_VEPLATE2] DEFAULT ('') NOT NULL,
    [VESTATE]    VARCHAR (MAX)   CONSTRAINT [DF_VEHICLE_VESTATE] DEFAULT ('') NOT NULL,
    [VECOCODE]   VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VECOCODE] DEFAULT ('') NOT NULL,
    [VEHO]       VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VEHO] DEFAULT ('') NOT NULL,
    [VEDIVISION] VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VEDIVISION] DEFAULT ('') NOT NULL,
    [VEDIVABBR]  VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VEDIVABBR] DEFAULT ('') NOT NULL,
    [VEGROUP]    VARCHAR (50)    CONSTRAINT [DF_VEHICLE_VEGROUP] DEFAULT ('') NOT NULL,
    [VECAT]      INT             CONSTRAINT [DF_VEHICLE_VECAT] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_VEHICLE] PRIMARY KEY CLUSTERED ([VEIDENT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [INDEX_VEHICLE_WHO]
    ON [dbo].[VEHICLE]([VEWHO] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_VEHICLE_INTNO]
    ON [dbo].[VEHICLE]([VEINTNO] ASC) WHERE ([VEINTNO]<>'');


GO
CREATE NONCLUSTERED INDEX [INDEX_VEHICLE_PLATE]
    ON [dbo].[VEHICLE]([VEPLATE] ASC) WHERE ([VEPLATE]<>'');


GO
CREATE NONCLUSTERED INDEX [INDEX_VEHICLE_PLATE2]
    ON [dbo].[VEHICLE]([VEPLATE2] ASC) WHERE ([VEPLATE2]<>'');


GO
CREATE NONCLUSTERED INDEX [INDEX_VEHICLE_VECOIDENT]
    ON [dbo].[VEHICLE]([VECOIDENT] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'ENABLE_BROKER', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VEHICLE';


GO
EXECUTE sp_addextendedproperty @name = N'EVENT NOTIFICATION', @value = N'TRUE', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'VEHICLE';

