
      CREATE VIEW [dbo].[CC_VEH_SUM]
      WITH  VIEW_METADATA
      AS
      SELECT dbo.SSTRUCTURE.SSHIIDENT,
      dbo.HIA_2.HIIDENT AS Expr1, dbo.SSTRUCTURE.SSSRIDENT, dbo.STRUCTURE.SRTITLE, dbo.STRUCTURE.SRLEVEL,
      dbo.STRUCTURE.SRNUMBER,
      dbo.HIA_2.VEPLATE,    dbo.HIA_2.VEINTNO,    dbo.HIA_2.PBNUMBER,     dbo.HIA_2.PBTITLE,    dbo.HIA_2.HIQUANT,    dbo.HIA_2.HITOTAL1,
      dbo.HIA_2.HITOTAL2,   dbo.HIA_2.HITOTAL3,   dbo.HIA_2.HITOTALVN,    dbo.HIA_2.HITOTALEB,  dbo.HIA_2.HITOTALEW,  dbo.HIA_2.HITOTALVAT, 
      dbo.HIA_2.HIINVTOTAL, dbo.HIA_2.HIINVPBASE, dbo.HIA_2.HIINVLPRICE,  dbo.HIA_2.HITRDATE
      FROM         dbo.SSTRUCTURE
      LEFT OUTER JOIN dbo.HIA_2     ON dbo.SSTRUCTURE.SSHIIDENT = dbo.HIA_2.HIIDENT 
      LEFT OUTER JOIN dbo.STRUCTURE ON dbo.SSTRUCTURE.SSSRIDENT = dbo.STRUCTURE.SRIDENT
      WHERE     (dbo.STRUCTURE.SRLEVEL = 3)
      WITH CHECK OPTION
    