
      CREATE VIEW [dbo].[EM_10] WITH  VIEW_METADATA
      AS
      SELECT     dbo.EMPLOYEE.EMIDENT, dbo.EMPLOYEE.EMDATE, dbo.EMPLOYEE.EMWHO, dbo.EMPLOYEE.EMPERSNO, dbo.EMPLOYEE.EMDRIVNO, dbo.EMPLOYEE.EMSTART,
      dbo.EMPLOYEE.EMEND, dbo.EMPLOYEE.EMTYPE, dbo.EMPLOYEE.EMLEIDENT, dbo.EMPLOYEE.EMCOIDENT, dbo.EMPLOYEE.EMADIDENT,
      dbo.EMPLOYEE.EMMEMO, dbo.EMPLOYEE.EMSTATE, dbo.EMPLOYEE.EMADCOMP, dbo.EMPLOYEE.EMISCUST, dbo.EMPLOYEE.EMCOID,
      dbo.EMPLOYEE.EMCOCODE, dbo.EMPLOYEE.EMHO,     dbo.EMPLOYEE.EMDIVISION,dbo.EMPLOYEE.EMDIVABBR, dbo.EMPLOYEE.EMGROUP,
      dbo.USLOG.USIDENT, dbo.USLOG.USDATE, dbo.USLOG.USWHO,
      dbo.USLOG.USNAME, dbo.USLOG.USADMIN, dbo.USLOG.USVALDATE, dbo.USLOG.USOVSEPS,
      dbo.ADDRESS.ADIDENT, dbo.ADDRESS.ADTYPE, dbo.ADDRESS.ADLOC, dbo.ADDRESS.ADZIP, dbo.ADDRESS.ADCTRY, dbo.ADDRESS.ADSTR, dbo.ADDRESS.ADHP,
      dbo.ADDRESS.ADPB, dbo.ADDRESS.ADFNAME1, dbo.ADDRESS.ADLNAME1, dbo.ADDRESS.ADTITLE1, dbo.ADDRESS.ADGEN1, dbo.ADDRESS.ADTEL1,
      dbo.ADDRESS.ADTEL2, dbo.ADDRESS.ADFAX1, dbo.ADDRESS.ADEMAIL1, dbo.ADDRESS.ADBANK1, dbo.ADDRESS.ADROUTNO1, dbo.ADDRESS.ADIBAN1,
      dbo.ADDRESS.ADACC1, dbo.ADDRESS.ADIBC1, dbo.ADDRESS.ADBANK2, dbo.ADDRESS.ADROUTNO2, dbo.ADDRESS.ADIBAN2, dbo.ADDRESS.ADACC2,
      dbo.ADDRESS.ADIBC2, OFFICE.ADIDENT AS OFADIDENT, OFFICE.ADTEL1 AS OFADTEL1, OFFICE.ADTEL2 AS OFADTEL2, OFFICE.ADFAX1 AS OFADFAX1,
      OFFICE.ADEMAIL1 AS OFADEMAIL1, dbo.COMPANY.COTITLE1, dbo.COMPANY.COTITLE2, dbo.COMPANY.COTITLE3, dbo.COMPANY.COCONO1,
      dbo.COMPANY.COCONO2, dbo.STRUCTURE.SRTITLE
      FROM         dbo.EMPLOYEE LEFT OUTER JOIN
      dbo.COMPANY ON dbo.EMPLOYEE.EMCOIDENT = dbo.COMPANY.COIDENT LEFT OUTER JOIN
      dbo.USLOG ON dbo.EMPLOYEE.EMWHO = dbo.USLOG.USIDENT LEFT OUTER JOIN
      dbo.ADDRESS ON dbo.EMPLOYEE.EMADIDENT = dbo.ADDRESS.ADIDENT LEFT OUTER JOIN
      dbo.ADDRESS AS OFFICE ON dbo.EMPLOYEE.EMADCOMP = OFFICE.ADIDENT LEFT OUTER JOIN
      dbo.STRUCTURE on dbo.EMPLOYEE.EMLEIDENT=dbo.STRUCTURE.SRIDENT
      WITH CHECK OPTION
    