
      CREATE VIEW [dbo].[EmployeeCardAutomat]
      WITH  VIEW_METADATA
      AS
      SELECT DISTINCT
      dbo.CARDS.CANO,       dbo.CARDS.CANO2,
      dbo.EMPLOYEE.EMPERSNO,dbo.EMPLOYEE.EMDRIVNO,
      dbo.ADDRESS.ADLOC,    dbo.ADDRESS.ADZIP,     dbo.ADDRESS.ADCTRY,    dbo.ADDRESS.ADSTR,  dbo.ADDRESS.ADFNAME1,
      dbo.ADDRESS.ADLNAME1, dbo.ADDRESS.ADTITLE1,  dbo.ADDRESS.ADGEN1,    dbo.ADDRESS.ADTEL1, dbo.ADDRESS.ADTEL2,
      dbo.AUTOMAT.AUNUMBER, dbo.AUTOMAT.AUTITLE,
      dbo.EMPLOYEE.EMCOIDENT
      FROM       dbo.EMPLOYEE
      INNER JOIN dbo.ADDRESS   ON dbo.EMPLOYEE.EMADIDENT  = dbo.ADDRESS.ADIDENT
      INNER JOIN dbo.CARDS     ON dbo.EMPLOYEE.EMIDENT    = dbo.CARDS.CAEMIDENT
      INNER JOIN dbo.REFERENCE ON dbo.CARDS.CAIDENT       = dbo.REFERENCE.RECAIDENT
      INNER JOIN dbo.AUTOMAT   ON dbo.REFERENCE.REAUIDENT = dbo.AUTOMAT.AUIDENT
      WITH CHECK OPTION
    