
        CREATE VIEW [dbo].[HIA_3]
        AS
        SELECT
        dbo.HIA.HIIDENT, dbo.HIA.HITRIDENT, dbo.HIA.HIDATE, dbo.HIA.HITRDATE, dbo.HIA.HITYPE, dbo.HIA.HIEXPDATE, dbo.HIA.HIAUIDENT, dbo.HIA.HICAIDENT,
        dbo.HIA.HIPBIDENT, dbo.HIA.HILPRICE, dbo.HIA.HILPRICE2, dbo.HIA.HIVAIDENT, dbo.HIA.HIQUANT, dbo.HIA.HITOTAL1, dbo.HIA.HITOTAL2, dbo.HIA.HIAIIDENT, dbo.HIA.HIPROT,
        dbo.HIA.HIFLIDENT, dbo.HIA.HIRECNO, dbo.HIA.HISTATE, dbo.HIA.HIINFO, dbo.HIA.HISTIDENT, dbo.HIA.HICONLTR, dbo.HIA.HIHIIDENT, dbo.HIA.HICON100,
        dbo.HIA.HICON1000, dbo.HIA.HICONREV, dbo.HIA.HIMILEAGE, dbo.HIA.HIFUIDENT,
        dbo.AUTOMAT.AUIDENT, dbo.AUTOMAT.AUDATE, dbo.AUTOMAT.AUWHO,
        dbo.AUTOMAT.AUNUMBER, dbo.AUTOMAT.AUTITLE, dbo.AUTOMAT.AURELEASE, dbo.AUTOMAT.AURELSUB, dbo.AUTOMAT.AUTYPE, dbo.AUTOMAT.AUAUTYPE,
        dbo.AUTOMAT.AUMEMO, dbo.AUTOMAT.AUSYSNO, dbo.AUTOMAT.AUACTIVE, dbo.AUTOMAT.AUSERIES,dbo.AUTOMAT.AUINTERN1, dbo.AUTOMAT.AUINTERN2,
        dbo.FUELSTAT.FUIDENT, dbo.FUELSTAT.FUDATE,
        dbo.FUELSTAT.FUWHO, dbo.FUELSTAT.FUTITLE, dbo.FUELSTAT.FUTITLE2, dbo.FUELSTAT.FUTITLE3, dbo.FUELSTAT.FUTYPE, dbo.FUELSTAT.FUNUMBER,
        dbo.FUELSTAT.FUADIDENT, dbo.FUELSTAT.FUMEMO, dbo.FUELSTAT.FUINTNO, dbo.FUELSTAT.FUINTNO2, dbo.FUELSTAT.FUSRIDENT,
        dbo.ADDRESS.ADIDENT,
        dbo.ADDRESS.ADWHO, dbo.ADDRESS.ADDATE, dbo.ADDRESS.ADTYPE, dbo.ADDRESS.ADLOC, dbo.ADDRESS.ADZIP, dbo.ADDRESS.ADCTRY, dbo.ADDRESS.ADSTR,
        dbo.ADDRESS.ADHP, dbo.ADDRESS.ADPB, dbo.ADDRESS.ADFNAME1, dbo.ADDRESS.ADLNAME1, dbo.ADDRESS.ADTITLE1, dbo.ADDRESS.ADGEN1,
        dbo.ADDRESS.ADTEL1, dbo.ADDRESS.ADTEL2, dbo.ADDRESS.ADFAX1, dbo.ADDRESS.ADEMAIL1, dbo.ADDRESS.ADBANK1, dbo.ADDRESS.ADROUTNO1,
        dbo.ADDRESS.ADIBAN1, dbo.ADDRESS.ADACC1, dbo.ADDRESS.ADIBC1, dbo.ADDRESS.ADBANK2, dbo.ADDRESS.ADROUTNO2, dbo.ADDRESS.ADIBAN2,
        dbo.ADDRESS.ADACC2, dbo.ADDRESS.ADIBC2,
        dbo.CARDS.CAIDENT, dbo.CARDS.CADATE, dbo.CARDS.CAWHO, dbo.CARDS.CANO, dbo.CARDS.CANO2, dbo.CARDS.CATYPE,
        dbo.CARDS.CALEIDENT, dbo.CARDS.CACOIDENT, dbo.CARDS.CAVEIDENT, dbo.CARDS.CAEMIDENT,
        dbo.COMPANY.COIDENT, dbo.COMPANY.CODATE,
        dbo.COMPANY.COWHO, dbo.COMPANY.COCONO1, dbo.COMPANY.COCONO2, dbo.COMPANY.COTITLE1, dbo.COMPANY.COTITLE2, dbo.COMPANY.COTITLE3,
        dbo.COMPANY.COMEMO, dbo.COMPANY.COADIDENT, dbo.COMPANY.COEND, dbo.COMPANY.COSTATE, dbo.COMPANY.COTYPE,
        dbo.VEHICLE.VEIDENT,
        dbo.VEHICLE.VEDATE, dbo.VEHICLE.VEWHO, dbo.VEHICLE.VEINTNO, dbo.VEHICLE.VEPLATE, dbo.VEHICLE.VEMEMO, dbo.VEHICLE.VEPBIDENT,
        dbo.VEHICLE.VEPGIDENT, dbo.VEHICLE.VESTART, dbo.VEHICLE.VEEND, dbo.VEHICLE.VELEIDENT, dbo.VEHICLE.VECOIDENT, dbo.VEHICLE.VECC,
        dbo.VEHICLE.VEEMIDENT, dbo.VEHICLE.VESTOC, dbo.VEHICLE.VESRIDENT, dbo.VEHICLE.VEMILES, dbo.VEHICLE.VEHOURS, dbo.VEHICLE.VETYPE,
        dbo.VEHICLE.VEKMOFFSET, dbo.VEHICLE.VEHHOFFSET, dbo.VEHICLE.VEOFFDATE, dbo.VEHICLE.VEKMSTART, dbo.VEHICLE.VEHHSTART, dbo.VEHICLE.VEPLATE2,
        dbo.VEHICLE.VESTATE,dbo.VEHICLE.VECAT,
        dbo.VTECH.VTIDENT,
        dbo.VTECH.VTTANK,     dbo.VTECH.VTNORM,       dbo.VTECH.VTPOS,       dbo.VTECH.VTNEG, 	dbo.VTECH.VTGVW,
        COMPANY_2.COIDENT AS COIDENT_2, COMPANY_2.CODATE AS CODATE_2, COMPANY_2.COWHO AS COWHO_2,
        COMPANY_2.COCONO1 AS COCONO1_2, COMPANY_2.COCONO2 AS COCONO2_2, COMPANY_2.COTITLE1 AS COTITLE1_2, COMPANY_2.COTITLE2 AS COTITLE2_2,
        COMPANY_2.COTITLE3 AS COTITLE3_2, COMPANY_2.COMEMO AS COMEMO_2, COMPANY_2.COADIDENT AS COADIDENT_2, COMPANY_2.COEND AS COEND_2,
        COMPANY_2.COSTATE AS COSTATE_2, COMPANY_2.COTYPE AS COTYPE_2,
        STRUCTURE_2.SRIDENT AS SRIDENT_2, STRUCTURE_2.SRDATE AS SRDATE_2,
        STRUCTURE_2.SRWHO AS SRWHO_2, STRUCTURE_2.SRNUMBER AS SRNUMBER_2, STRUCTURE_2.SRTITLE AS SRTITLE_2,
        STRUCTURE_2.SRMEMO AS SRMEMO_2, STRUCTURE_2.SRADIDENT AS SRADIDENT_2, STRUCTURE_2.SRSRIDENT AS SRSRIDENT_2,
        STRUCTURE_2.SRLEVEL AS SRLEVEL_2, STRUCTURE_2.SRIMAGE AS SRIMAGE_2, STRUCTURE_2.SRHLEVEL AS SRHLEVEL_2,
        dbo.EMPLOYEE.EMIDENT,
        dbo.EMPLOYEE.EMDATE, dbo.EMPLOYEE.EMWHO, dbo.EMPLOYEE.EMPERSNO, dbo.EMPLOYEE.EMDRIVNO, dbo.EMPLOYEE.EMSTART, dbo.EMPLOYEE.EMEND,
        dbo.EMPLOYEE.EMTYPE, dbo.EMPLOYEE.EMLEIDENT, dbo.EMPLOYEE.EMCOIDENT, dbo.EMPLOYEE.EMADIDENT, dbo.EMPLOYEE.EMMEMO,
        dbo.EMPLOYEE.EMSTATE, dbo.EMPLOYEE.EMISCUST, dbo.EMPLOYEE.EMCOID,
        COMPANY_1.COIDENT AS COIDENT_1, COMPANY_1.CODATE AS CODATE_1, COMPANY_1.COWHO AS COWHO_1,
        COMPANY_1.COCONO1 AS COCONO1_1, COMPANY_1.COCONO2 AS COCONO2_1, COMPANY_1.COTITLE1 AS COTITLE1_1, COMPANY_1.COTITLE2 AS COTITLE2_1,
        COMPANY_1.COTITLE3 AS COTITLE3_1, COMPANY_1.COMEMO AS COMEMO_1, COMPANY_1.COADIDENT AS COADIDENT_1, COMPANY_1.COEND AS COEND_1,
        COMPANY_1.COSTATE AS COSTATE_1, COMPANY_1.COTYPE AS COTYPE_1,
        STRUCTURE_1.SRIDENT AS SRIDENT_1, STRUCTURE_1.SRDATE AS SRDATE_1,
        STRUCTURE_1.SRWHO AS SRWHO_1, STRUCTURE_1.SRNUMBER AS SRNUMBER_1, STRUCTURE_1.SRTITLE AS SRTITLE_1,
        STRUCTURE_1.SRMEMO AS SRMEMO_1, STRUCTURE_1.SRADIDENT AS SRADIDENT_1, STRUCTURE_1.SRSRIDENT AS SRSRIDENT_1,
        STRUCTURE_1.SRLEVEL AS SRLEVEL_1, STRUCTURE_1.SRIMAGE AS SRIMAGE_1, STRUCTURE_1.SRHLEVEL AS SRHLEVEL_1,
        ADDRESS_2.ADIDENT AS ADIDENT_2, ADDRESS_2.ADWHO AS ADWHO_2, ADDRESS_2.ADTYPE AS ADTYPE_2, ADDRESS_2.ADLOC AS ADLOC_2,
        ADDRESS_2.ADZIP AS ADZIP_2, ADDRESS_2.ADCTRY AS ADCTRY_2, ADDRESS_2.ADSTR AS ADSTR_2, ADDRESS_2.ADHP AS ADHP_2,
        ADDRESS_2.ADPB AS ADPB_2, ADDRESS_2.ADFNAME1 AS ADFNAME1_2, ADDRESS_2.ADLNAME1 AS ADLNAME1_2, ADDRESS_2.ADTITLE1 AS ADTITLE1_2,
        ADDRESS_2.ADGEN1 AS ADGEN1_2, ADDRESS_2.ADTEL1 AS ADTEL1_2, ADDRESS_2.ADTEL2 AS ADTEL2_2, ADDRESS_2.ADFAX1 AS ADFAX1_2,
        ADDRESS_2.ADEMAIL1 AS ADEMAIL1_2, ADDRESS_2.ADBANK1 AS ADBANK1_2, ADDRESS_2.ADROUTNO1 AS ADROUTNO1_2, ADDRESS_2.ADIBAN1 AS ADIBAN1_2,
        ADDRESS_2.ADACC1 AS ADACC1_2, ADDRESS_2.ADIBC1 AS ADIBC1_2, ADDRESS_2.ADBANK2 AS ADBANK2_2, ADDRESS_2.ADROUTNO2 AS ADROUTNO2_2,
        ADDRESS_2.ADIBAN2 AS ADIBAN2_2, ADDRESS_2.ADACC2 AS ADACC2_2, ADDRESS_2.ADIBC2 AS ADIBC2_2,
        dbo.PBASE.PBIDENT, dbo.PBASE.PBDATE,
        dbo.PBASE.PBWHO, dbo.PBASE.PBTITLE, dbo.PBASE.PBNUMBER, dbo.PBASE.PBMEMO, dbo.PBASE.PBPGIDENT, dbo.PBASE.PBPTIDENT, dbo.PBASE.PBEXTERN,
        dbo.PBASE.PBEAN, dbo.PBASE.PBDISPL, dbo.PBASE.PBVAIDENT,
        dbo.VAT.VAIDENT, dbo.VAT.VADATE, dbo.VAT.VAWHO, dbo.VAT.VAVAT, dbo.VAT.VATYPE,
        dbo.VAT.VANUMBER, dbo.VAT.VATITLE, dbo.STORAGE.STIDENT, dbo.STORAGE.STDATE, dbo.STORAGE.STWHO, dbo.STORAGE.STTITLE, dbo.STORAGE.STNUMBER,
        dbo.STORAGE.STMEMO, dbo.STORAGE.STPBIDENT, dbo.STORAGE.STMIN, dbo.STORAGE.STMAX, dbo.STORAGE.STORDER, dbo.STORAGE.STUNIT,
        dbo.STORAGE.STMINORDER, dbo.STORAGE.STORDERED, dbo.STORAGE.STORDATE, dbo.STORAGE.STINV, dbo.STORAGE.STAUTO, dbo.STORAGE.STAMOUNT,
        dbo.STORAGE.STAMAUTO, dbo.STORAGE.STAMDATE, dbo.STORAGE.STPROBE, dbo.STORAGE.STMEASURE, dbo.STORAGE.STMEDATE,
        dbo.inputadd.iptitle,
        dbo.SCHARAC.SCHIIDENT, dbo.SCHARAC.SCVCIDENT,
        dbo.VCHARAC.VCIDENT,
        dbo.VCHARAC.VCTITLE, dbo.VCHARAC.VCVFIDENT,
        dbo.HIA.HICAIDENT2
        FROM         dbo.HIA LEFT OUTER JOIN
        dbo.SCHARAC                   ON    dbo.HIA.HIIDENT         = dbo.SCHARAC.SCHIIDENT LEFT OUTER JOIN
        dbo.VCHARAC                   ON    dbo.VCHARAC.VCIDENT     = dbo.SCHARAC.SCVCIDENT LEFT OUTER JOIN
        dbo.AUTOMAT                   ON    dbo.HIA.HIAUIDENT       = dbo.AUTOMAT.AUIDENT LEFT OUTER JOIN
        dbo.FUELSTAT                  ON    dbo.HIA.HIFUIDENT       = dbo.FUELSTAT.FUIDENT LEFT OUTER JOIN
        dbo.ADDRESS                   ON    dbo.FUELSTAT.FUADIDENT  = dbo.ADDRESS.ADIDENT LEFT OUTER JOIN
        dbo.CARDS                     ON    dbo.HIA.HICAIDENT       = dbo.CARDS.CAIDENT LEFT OUTER JOIN
        dbo.COMPANY                   ON    dbo.CARDS.CACOIDENT     = dbo.COMPANY.COIDENT LEFT OUTER JOIN
        dbo.VEHICLE                   ON    dbo.HIA.HIVEIDENT       = dbo.VEHICLE.VEIDENT LEFT OUTER JOIN
        dbo.VTECH                     ON    dbo.VEHICLE.VEIDENT     = dbo.VTECH.VTIDENT          LEFT OUTER JOIN
        dbo.COMPANY AS COMPANY_2      ON    dbo.VEHICLE.VECOIDENT   = COMPANY_2.COIDENT LEFT OUTER JOIN
        dbo.STRUCTURE AS STRUCTURE_2  ON    dbo.VEHICLE.VELEIDENT   = STRUCTURE_2.SRIDENT LEFT OUTER JOIN
        dbo.EMPLOYEE                  ON    dbo.HIA.HIEMIDENT       = dbo.EMPLOYEE.EMIDENT LEFT OUTER JOIN
        dbo.COMPANY AS COMPANY_1      ON    dbo.EMPLOYEE.EMCOIDENT  = COMPANY_1.COIDENT LEFT OUTER JOIN
        dbo.STRUCTURE AS STRUCTURE_1  ON    dbo.EMPLOYEE.EMLEIDENT  = STRUCTURE_1.SRIDENT LEFT OUTER JOIN
        dbo.ADDRESS AS ADDRESS_2      ON    dbo.EMPLOYEE.EMADIDENT  = ADDRESS_2.ADIDENT LEFT OUTER JOIN
        dbo.PBASE                     ON    dbo.HIA.HIPBIDENT       = dbo.PBASE.PBIDENT LEFT OUTER JOIN
        dbo.VAT                       ON    dbo.HIA.HIVAIDENT       = dbo.VAT.VAIDENT LEFT OUTER JOIN
        dbo.STORAGE                   ON    dbo.HIA.HISTIDENT       = dbo.STORAGE.STIDENT LEFT OUTER JOIN
        dbo.INPUTADD                  ON    dbo.HIA.HIIPIDENT       = dbo.inputadd.IPIDENT
        WHERE     (dbo.SCHARAC.SCIDENT > 0)
      