
      CREATE VIEW [dbo].[HIA_2]
      AS
      SELECT TOP (100) PERCENT
      dbo.HIA.HIIDENT,       dbo.HIA.HITRIDENT,     dbo.HIA.HIDATE,        dbo.HIA.HITRDATE,      dbo.HIA.HITRDATSTA,    dbo.HIA.HITRDATEND,    dbo.HIA.HITRDUR,       dbo.HIA.HITYPE,
      dbo.HIA.HIPUIDENT,     dbo.HIA.HIPUVALUE,     dbo.HIA.HIEXPDATE,     dbo.HIA.HIAUIDENT,     dbo.HIA.HICAIDENT,
      dbo.HIA.HIPBIDENT,     dbo.HIA.HILPRICE,      dbo.HIA.HILPRICE2,     dbo.HIA.HILPRICE3,     dbo.HIA.HILPRICEVN,    dbo.HIA.HILPRICEEB,    dbo.HIA.HILPRICEEW,    dbo.HIA.HIVAIDENT,
      dbo.HIA.HIQUANT,       dbo.HIA.HITOTAL1,      dbo.HIA.HITOTAL2,      dbo.HIA.HITOTAL3,      dbo.HIA.HITOTALVN,     dbo.HIA.HITOTALEB,     dbo.HIA.HITOTALEW,     dbo.HIA.HITOTALVAT,
      dbo.HIA.HIINVLPRICE,   dbo.HIA.HIINVTOTAL,    dbo.HIA.HIINVPBASE,    dbo.HIA.HIAIIDENT,
      dbo.HIA.HIPROT,        dbo.HIA.HIFLIDENT,     dbo.HIA.HIRECNO,       dbo.HIA.HISTATE,       dbo.HIA.HIINFO,        dbo.HIA.HIINFO2,       dbo.HIA.HISTIDENT,     dbo.HIA.HICONLTR,
      dbo.HIA.HIHIIDENT,     dbo.HIA.HICON100,      dbo.HIA.HICON1000,     dbo.HIA.HICONREV,      dbo.HIA.HIMILEAGE,     dbo.HIA.HIFUIDENT,     dbo.HIA.HICAIDENT2,    dbo.HIA.HIINTERN,
      dbo.HIA.HIEMIDENT,     dbo.HIA.HIEMCAIDENT,   dbo.HIA.HIVEIDENT,     dbo.HIA.HIVECAIDENT,   dbo.HIA.HIIVIDENT,     dbo.HIA.HIMEMO,        dbo.HIA.HICO2AV,       dbo.HIA.HICO2,
      dbo.HIA.HIGAINL,       dbo.HIA.HIGAIN,        dbo.HIA.HIDIAL1,       dbo.HIA.HIDIAL2,       dbo.HIA.HIDIAL3,       dbo.HIA.HIDIAL4,       dbo.HIA.HIDIAL5,
      dbo.HIA.HITOLLTT,      dbo.HIA.HITOLLTO,      dbo.HIA.HITOLLTZ,      dbo.HIA.HITOLLTA,      dbo.HIA.HITOLLTG,      dbo.HIA.HITOLLTM,      dbo.HIA.HITOLLIS,      dbo.HIA.HITOLLTY,
      dbo.HIA.HIMAN,         dbo.HIA.HILK,          dbo.HIA.HITOTQUANTITY, dbo.HIA.HITOTAMOUNT,   dbo.HIA.HINOZZLE,      dbo.HIA.HITOTADIFF,    dbo.HIA.HITOTQDIFF,    dbo.HIA.HIIPIDENT,
      dbo.HIA.HIINVPEXTRA,   dbo.HIA.HIINVPEXVAL,   dbo.HIA.HIPRTYPE,
      dbo.AUTOMAT.AUIDENT,
      dbo.AUTOMAT.AUDATE,    dbo.AUTOMAT.AUWHO,     dbo.AUTOMAT.AUNUMBER,  dbo.AUTOMAT.AUTITLE,   dbo.AUTOMAT.AURELEASE, dbo.AUTOMAT.AURELSUB,  dbo.AUTOMAT.AUTYPE,    dbo.AUTOMAT.AUAUTYPE,
      dbo.AUTOMAT.AUMEMO,    dbo.AUTOMAT.AUSYSNO,   dbo.AUTOMAT.AUACTIVE,  dbo.AUTOMAT.AUSERIES,  dbo.AUTOMAT.AUINTERN1, dbo.AUTOMAT.AUINTERN2,
      dbo.FUELSTAT.FUIDENT,  dbo.FUELSTAT.FUDATE,   dbo.FUELSTAT.FUWHO,    dbo.FUELSTAT.FUTITLE,  dbo.FUELSTAT.FUTITLE2, dbo.FUELSTAT.FUTITLE3, dbo.FUELSTAT.FUTYPE,   dbo.FUELSTAT.FUNUMBER,
      dbo.FUELSTAT.FUADIDENT,dbo.FUELSTAT.FUMEMO,   dbo.FUELSTAT.FUINTNO,  dbo.FUELSTAT.FUINTNO2, dbo.FUELSTAT.FUSRIDENT,
      dbo.ADDRESS.ADIDENT,
      dbo.ADDRESS.ADWHO,     dbo.ADDRESS.ADDATE,    dbo.ADDRESS.ADTYPE,    dbo.ADDRESS.ADLOC,     dbo.ADDRESS.ADZIP,     dbo.ADDRESS.ADCTRY,    dbo.ADDRESS.ADSTR,     dbo.ADDRESS.ADHP,
      dbo.ADDRESS.ADPB,      dbo.ADDRESS.ADFNAME1,  dbo.ADDRESS.ADLNAME1,  dbo.ADDRESS.ADTITLE1,  dbo.ADDRESS.ADGEN1,    dbo.ADDRESS.ADTEL1,    dbo.ADDRESS.ADTEL2,    dbo.ADDRESS.ADFAX1,
      dbo.ADDRESS.ADEMAIL1,  dbo.ADDRESS.ADBANK1,   dbo.ADDRESS.ADROUTNO1, dbo.ADDRESS.ADIBAN1,   dbo.ADDRESS.ADACC1,    dbo.ADDRESS.ADIBC1,    dbo.ADDRESS.ADBANK2,   dbo.ADDRESS.ADROUTNO2,
      dbo.ADDRESS.ADIBAN2,   dbo.ADDRESS.ADACC2,    dbo.ADDRESS.ADIBC2,    dbo.ADDRESS.ADVATID,
      dbo.CARDS.CAIDENT,
      dbo.CARDS.CADATE,      dbo.CARDS.CAWHO,       dbo.CARDS.CANO,        dbo.CARDS.CATYPE,      dbo.CARDS.CALEIDENT,   dbo.CARDS.CACOIDENT,   dbo.CARDS.CAVEIDENT,   dbo.CARDS.CAEMIDENT,
      dbo.CARDS.CANO2,
      dbo.COMPANY.COIDENT,   dbo.COMPANY.CODATE,    dbo.COMPANY.COWHO,     dbo.COMPANY.COCONO1,   dbo.COMPANY.COCONO2,   dbo.COMPANY.COTITLE1,  dbo.COMPANY.COTITLE2,  dbo.COMPANY.COTITLE3,
      dbo.COMPANY.COMEMO,    dbo.COMPANY.COADIDENT, dbo.COMPANY.COEND,     dbo.COMPANY.COSTATE,   dbo.COMPANY.COTYPE,
      ADDRESS_3.ADIDENT      AS ADIDENT_3,
      ADDRESS_3.ADWHO        AS ADWHO_3,            ADDRESS_3.ADTYPE       AS ADTYPE_3,
      ADDRESS_3.ADLOC        AS ADLOC_3,            ADDRESS_3.ADZIP        AS ADZIP_3,
      ADDRESS_3.ADCTRY       AS ADCTRY_3,           ADDRESS_3.ADSTR        AS ADSTR_3,
      ADDRESS_3.ADHP         AS ADHP_3,             ADDRESS_3.ADPB         AS ADPB_3,
      ADDRESS_3.ADFNAME1     AS ADFNAME1_3,         ADDRESS_3.ADLNAME1     AS ADLNAME1_3,
      ADDRESS_3.ADTITLE1     AS ADTITLE1_3,         ADDRESS_3.ADGEN1       AS ADGEN1_3,
      ADDRESS_3.ADTEL1       AS ADTEL1_3,           ADDRESS_3.ADTEL2       AS ADTEL2_3,
      ADDRESS_3.ADFAX1       AS ADFAX1_3,           ADDRESS_3.ADEMAIL1     AS ADEMAIL1_3,
      ADDRESS_3.ADBANK1      AS ADBANK1_3,          ADDRESS_3.ADROUTNO1    AS ADROUTNO1_3,
      ADDRESS_3.ADIBAN1      AS ADIBAN1_3,          ADDRESS_3.ADACC1       AS ADACC1_3,
      ADDRESS_3.ADIBC1       AS ADIBC1_3,           ADDRESS_3.ADBANK2      AS ADBANK2_3,
      ADDRESS_3.ADROUTNO2    AS ADROUTNO2_3,        ADDRESS_3.ADIBAN2      AS ADIBAN2_3,
      ADDRESS_3.ADACC2       AS ADACC2_3,           ADDRESS_3.ADIBC2       AS ADIBC2_3,
      ADDRESS_3.ADVATID      AS ADVATID_3,
      dbo.VEHICLE.VEIDENT,
      dbo.VEHICLE.VEDATE,    dbo.VEHICLE.VEWHO,     dbo.VEHICLE.VEINTNO,   dbo.VEHICLE.VEPLATE,   dbo.VEHICLE.VEMEMO,    dbo.VEHICLE.VEPBIDENT, dbo.VEHICLE.VEPGIDENT, dbo.VEHICLE.VESTART,
      dbo.VEHICLE.VEEND,     dbo.VEHICLE.VELEIDENT, dbo.VEHICLE.VECOIDENT, dbo.VEHICLE.VECC,      dbo.VEHICLE.VEEMIDENT, dbo.VEHICLE.VESTOC,    dbo.VEHICLE.VESRIDENT, dbo.VEHICLE.VEMILES,
      dbo.VEHICLE.VEHOURS,   dbo.VEHICLE.VETYPE,    dbo.VEHICLE.VEKMOFFSET,dbo.VEHICLE.VEHHOFFSET,dbo.VEHICLE.VEOFFDATE, dbo.VEHICLE.VEKMSTART, dbo.VEHICLE.VEHHSTART, dbo.VEHICLE.VEPLATE2,
      dbo.VEHICLE.VESTATE,   dbo.VEHICLE.VECOCODE,  dbo.VEHICLE.VEHO,      dbo.VEHICLE.VEDIVISION,dbo.VEHICLE.VEDIVABBR, dbo.VEHICLE.VEGROUP,   dbo.VEHICLE.VEVEHNO,   dbo.VEHICLE.VECAT,
      dbo.VTECH.VTIDENT,
      dbo.VTECH.VTTANK,      dbo.VTECH.VTNORM,      dbo.VTECH.VTPOS,       dbo.VTECH.VTNEG,       dbo.VTECH.VTCO2,       dbo.VTECH.VTGVW,
      COMPANY_2.COIDENT      AS COIDENT_2,
      COMPANY_2.CODATE       AS CODATE_2,           COMPANY_2.COWHO        AS COWHO_2,
      COMPANY_2.COCONO1      AS COCONO1_2,          COMPANY_2.COCONO2      AS COCONO2_2,
      COMPANY_2.COTITLE1     AS COTITLE1_2,         COMPANY_2.COTITLE2     AS COTITLE2_2,
      COMPANY_2.COTITLE3     AS COTITLE3_2,         COMPANY_2.COMEMO       AS COMEMO_2,
      COMPANY_2.COADIDENT    AS COADIDENT_2,        COMPANY_2.COEND        AS COEND_2,
      COMPANY_2.COSTATE      AS COSTATE_2,          COMPANY_2.COTYPE       AS COTYPE_2,
      CARDS_2.CAIDENT        AS CAIDENT_2,
      CARDS_2.CADATE         AS CADATE_2,           CARDS_2.CAWHO          AS CAWHO_2,
      CARDS_2.CANO           AS CANO_2,             CARDS_2.CATYPE         AS CATYPE_2,
      CARDS_2.CALEIDENT      AS CALEIDENT_2,        CARDS_2.CACOIDENT      AS CACOIDENT_2,
      CARDS_2.CAVEIDENT      AS CAVEIDENT_2,        CARDS_2.CAEMIDENT      AS CAEMIDENT_2,
      CARDS_2.CANO2          AS CANO2_2,
      COMPANY_3.COIDENT      AS COIDENT_3,
      COMPANY_3.CODATE       AS CODATE_3,           COMPANY_3.COWHO        AS COWHO_3,
      COMPANY_3.COCONO1      AS COCONO1_3,          COMPANY_3.COCONO2      AS COCONO2_3,
      COMPANY_3.COTITLE1     AS COTITLE1_3,         COMPANY_3.COTITLE2     AS COTITLE2_3,
      COMPANY_3.COTITLE3     AS COTITLE3_3,         COMPANY_3.COMEMO       AS COMEMO_3,
      COMPANY_3.COADIDENT    AS COADIDENT_3,        COMPANY_3.COEND        AS COEND_3,
      COMPANY_3.COSTATE      AS COSTATE_3,          COMPANY_3.COTYPE       AS COTYPE_3,
      STRUCTURE_2.SRIDENT    AS SRIDENT_2,
      STRUCTURE_2.SRDATE     AS SRDATE_2,           STRUCTURE_2.SRWHO      AS SRWHO_2,
      STRUCTURE_2.SRNUMBER   AS SRNUMBER_2,         STRUCTURE_2.SRTITLE    AS SRTITLE_2,
      STRUCTURE_2.SRMEMO     AS SRMEMO_2,           STRUCTURE_2.SRADIDENT  AS SRADIDENT_2,
      STRUCTURE_2.SRSRIDENT  AS SRSRIDENT_2,        STRUCTURE_2.SRLEVEL    AS SRLEVEL_2,
      STRUCTURE_2.SRIMAGE    AS SRIMAGE_2,          STRUCTURE_2.SRHLEVEL   AS SRHLEVEL_2,
      dbo.EMPLOYEE.EMIDENT,
      dbo.EMPLOYEE.EMDATE,   dbo.EMPLOYEE.EMWHO,    dbo.EMPLOYEE.EMPERSNO, dbo.EMPLOYEE.EMDRIVNO, dbo.EMPLOYEE.EMSTART,  dbo.EMPLOYEE.EMEND,    dbo.EMPLOYEE.EMTYPE,   dbo.EMPLOYEE.EMLEIDENT,
      dbo.EMPLOYEE.EMCOIDENT,dbo.EMPLOYEE.EMADIDENT,dbo.EMPLOYEE.EMMEMO,   dbo.EMPLOYEE.EMSTATE,  dbo.EMPLOYEE.EMISCUST, dbo.EMPLOYEE.EMCOID,
      dbo.EMPLOYEE.EMCOCODE, dbo.EMPLOYEE.EMHO,     dbo.EMPLOYEE.EMDIVISION,dbo.EMPLOYEE.EMDIVABBR, dbo.EMPLOYEE.EMGROUP,
      COMPANY_1.COIDENT      AS COIDENT_1,
      COMPANY_1.CODATE       AS CODATE_1,           COMPANY_1.COWHO        AS COWHO_1,
      COMPANY_1.COCONO1      AS COCONO1_1,          COMPANY_1.COCONO2      AS COCONO2_1,
      COMPANY_1.COTITLE1     AS COTITLE1_1,         COMPANY_1.COTITLE2     AS COTITLE2_1,
      COMPANY_1.COTITLE3     AS COTITLE3_1,         COMPANY_1.COMEMO       AS COMEMO_1,
      COMPANY_1.COADIDENT    AS COADIDENT_1,        COMPANY_1.COEND        AS COEND_1,
      COMPANY_1.COSTATE      AS COSTATE_1,          COMPANY_1.COTYPE       AS COTYPE_1,
      STRUCTURE_1.SRIDENT    AS SRIDENT_1,
      STRUCTURE_1.SRDATE     AS SRDATE_1,           STRUCTURE_1.SRWHO      AS SRWHO_1,
      STRUCTURE_1.SRNUMBER   AS SRNUMBER_1,         STRUCTURE_1.SRTITLE    AS SRTITLE_1,
      STRUCTURE_1.SRMEMO     AS SRMEMO_1,           STRUCTURE_1.SRADIDENT  AS SRADIDENT_1,
      STRUCTURE_1.SRSRIDENT  AS SRSRIDENT_1,        STRUCTURE_1.SRLEVEL    AS SRLEVEL_1,
      STRUCTURE_1.SRIMAGE    AS SRIMAGE_1,          STRUCTURE_1.SRHLEVEL   AS SRHLEVEL_1,
      ADDRESS_2.ADIDENT      AS ADIDENT_2,
      ADDRESS_2.ADWHO        AS ADWHO_2,            ADDRESS_2.ADTYPE       AS ADTYPE_2,
      ADDRESS_2.ADLOC        AS ADLOC_2,            ADDRESS_2.ADZIP        AS ADZIP_2,
      ADDRESS_2.ADCTRY       AS ADCTRY_2,           ADDRESS_2.ADSTR        AS ADSTR_2,
      ADDRESS_2.ADHP         AS ADHP_2,             ADDRESS_2.ADPB         AS ADPB_2,
      ADDRESS_2.ADFNAME1     AS ADFNAME1_2,         ADDRESS_2.ADLNAME1     AS ADLNAME1_2,
      ADDRESS_2.ADTITLE1     AS ADTITLE1_2,         ADDRESS_2.ADGEN1       AS ADGEN1_2,
      ADDRESS_2.ADTEL1       AS ADTEL1_2,           ADDRESS_2.ADTEL2       AS ADTEL2_2,
      ADDRESS_2.ADFAX1       AS ADFAX1_2,           ADDRESS_2.ADEMAIL1     AS ADEMAIL1_2,
      ADDRESS_2.ADBANK1      AS ADBANK1_2,          ADDRESS_2.ADROUTNO1    AS ADROUTNO1_2,
      ADDRESS_2.ADIBAN1      AS ADIBAN1_2,          ADDRESS_2.ADACC1       AS ADACC1_2,
      ADDRESS_2.ADIBC1       AS ADIBC1_2,           ADDRESS_2.ADBANK2      AS ADBANK2_2,
      ADDRESS_2.ADROUTNO2    AS ADROUTNO2_2,        ADDRESS_2.ADIBAN2      AS ADIBAN2_2,
      ADDRESS_2.ADACC2       AS ADACC2_2,           ADDRESS_2.ADIBC2       AS ADIBC2_2,
      ADDRESS_2.ADVATID      AS ADVATID_2,
      ADDRESS_4.ADIDENT      AS ADIDENT_4,
      ADDRESS_4.ADWHO        AS ADWHO_4,            ADDRESS_4.ADTYPE       AS ADTYPE_4,
      ADDRESS_4.ADLOC        AS ADLOC_4,            ADDRESS_4.ADZIP        AS ADZIP_4,
      ADDRESS_4.ADCTRY       AS ADCTRY_4,           ADDRESS_4.ADSTR        AS ADSTR_4,
      ADDRESS_4.ADHP         AS ADHP_4,             ADDRESS_4.ADPB         AS ADPB_4,
      ADDRESS_4.ADFNAME1     AS ADFNAME1_4,         ADDRESS_4.ADLNAME1     AS ADLNAME1_4,
      ADDRESS_4.ADTITLE1     AS ADTITLE1_4,         ADDRESS_4.ADGEN1       AS ADGEN1_4,
      ADDRESS_4.ADTEL1       AS ADTEL1_4,           ADDRESS_4.ADTEL2       AS ADTEL2_4,
      ADDRESS_4.ADFAX1       AS ADFAX1_4,           ADDRESS_4.ADEMAIL1     AS ADEMAIL1_4,
      ADDRESS_4.ADBANK1      AS ADBANK1_4,          ADDRESS_4.ADROUTNO1    AS ADROUTNO1_4,
      ADDRESS_4.ADIBAN1      AS ADIBAN1_4,          ADDRESS_4.ADACC1       AS ADACC1_4,
      ADDRESS_4.ADIBC1       AS ADIBC1_4,           ADDRESS_4.ADBANK2      AS ADBANK2_4,
      ADDRESS_4.ADROUTNO2    AS ADROUTNO2_4,        ADDRESS_4.ADIBAN2      AS ADIBAN2_4,
      ADDRESS_4.ADACC2       AS ADACC2_4,           ADDRESS_4.ADIBC2       AS ADIBC2_4,
      ADDRESS_4.ADVATID      AS ADVATID_4,
      ADDRESS_5.ADIDENT      AS ADIDENT_5,
      ADDRESS_5.ADWHO        AS ADWHO_5,            ADDRESS_5.ADTYPE       AS ADTYPE_5,
      ADDRESS_5.ADLOC        AS ADLOC_5,            ADDRESS_5.ADZIP        AS ADZIP_5,
      ADDRESS_5.ADCTRY       AS ADCTRY_5,           ADDRESS_5.ADSTR        AS ADSTR_5,
      ADDRESS_5.ADHP         AS ADHP_5,             ADDRESS_5.ADPB         AS ADPB_5,
      ADDRESS_5.ADFNAME1     AS ADFNAME1_5,         ADDRESS_5.ADLNAME1     AS ADLNAME1_5,
      ADDRESS_5.ADTITLE1     AS ADTITLE1_5,         ADDRESS_5.ADGEN1       AS ADGEN1_5,
      ADDRESS_5.ADTEL1       AS ADTEL1_5,           ADDRESS_5.ADTEL2       AS ADTEL2_5,
      ADDRESS_5.ADFAX1       AS ADFAX1_5,           ADDRESS_5.ADEMAIL1     AS ADEMAIL1_5,
      ADDRESS_5.ADBANK1      AS ADBANK1_5,          ADDRESS_5.ADROUTNO1    AS ADROUTNO1_5,
      ADDRESS_5.ADIBAN1      AS ADIBAN1_5,          ADDRESS_5.ADACC1       AS ADACC1_5,
      ADDRESS_5.ADIBC1       AS ADIBC1_5,           ADDRESS_5.ADBANK2      AS ADBANK2_5,
      ADDRESS_5.ADROUTNO2    AS ADROUTNO2_5,        ADDRESS_5.ADIBAN2      AS ADIBAN2_5,
      ADDRESS_5.ADACC2       AS ADACC2_5,           ADDRESS_5.ADIBC2       AS ADIBC2_5,
      ADDRESS_5.ADVATID      AS ADVATID_5,
      dbo.PBASE.PBIDENT,
      dbo.PBASE.PBDATE,      dbo.PBASE.PBWHO,       dbo.PBASE.PBTITLE,     dbo.PBASE.PBNUMBER,    dbo.PBASE.PBMEMO,      dbo.PBASE.PBPGIDENT,   dbo.PBASE.PBPTIDENT,   dbo.PBASE.PBEXTERN,
      dbo.PBASE.PBEAN,       dbo.PBASE.PBDISPL,     dbo.PBASE.PBVAIDENT,   dbo.PBASE.PBTYPE,      dbo.PBASE.PBIMPORT,
      dbo.PBASE.PBNSCNUM,    dbo.PBASE.PBNSCRCPT,   dbo.PBASE.PBNSCONLT,   dbo.PBASE.PBNSCONLN,   dbo.PBASE.PBNSCPTF1,   dbo.PBASE.PBNSCPTF2,
      dbo.PGROUP.PGIDENT,    dbo.PGROUP.PGDATE,     dbo.PGROUP.PGWHO,      dbo.PGROUP.PGTITLE,    dbo.PGROUP.PGNUMBER,
      dbo.PGROUP.PGMEMO,     dbo.PGROUP.PGFLTYPE,   dbo.PGROUP.PGCO2,
      dbo.PTYPE.PTIDENT,     dbo.PTYPE.PTDATE,      dbo.PTYPE.PTWHO,       dbo.PTYPE.PTTITLE,     dbo.PTYPE.PTNUMBER,
      dbo.PTYPE.PTMEMO,      dbo.PTYPE.PTQUIDENT,   dbo.PTYPE.PTTYPE,      dbo.PTYPE.PTFLTYPE,
      dbo.VAT.VAIDENT,
      dbo.VAT.VADATE,        dbo.VAT.VAWHO,         dbo.VAT.VAVAT,         dbo.VAT.VATYPE,        dbo.VAT.VANUMBER,      dbo.VAT.VATITLE,
      dbo.STORAGE.STIDENT,
      dbo.STORAGE.STDATE,    dbo.STORAGE.STWHO,     dbo.STORAGE.STTITLE,   dbo.STORAGE.STNUMBER,  dbo.STORAGE.STMEMO,    dbo.STORAGE.STPBIDENT, dbo.STORAGE.STMIN,     dbo.STORAGE.STMAX,
      dbo.STORAGE.STORDER,   dbo.STORAGE.STUNIT,    dbo.STORAGE.STMINORDER,dbo.STORAGE.STORDERED, dbo.STORAGE.STORDATE,  dbo.STORAGE.STINV,     dbo.STORAGE.STAUTO,    dbo.STORAGE.STAMOUNT,
      dbo.STORAGE.STAMAUTO,  dbo.STORAGE.STAMDATE,  dbo.STORAGE.STPROBE,   dbo.STORAGE.STMEASURE, dbo.STORAGE.STMEDATE,
      dbo.INPUTADD.IPTITLE,  dbo.INPUTADD.IPNUMBER, dbo.INPUTADD.IPMEMO,
      dbo.ADISP.AINUM,       dbo.ADISP.AISTATE,     dbo.ADISP.AIEXTERN,    dbo.ADISP.AIEXTREF,
      FLEET_2.FETITLE        AS FETITLE_2,
      EMPLOYEE_1.EMIDENT     as EMIDENT_1,          EMPLOYEE_1.EMCOID      AS EMCOID_1,
      dbo.INVOICE.IVNO,      dbo.INVOICE.IVIDATE,   dbo.INVOICE.IVIDENT,
      dbo.PREPAID.PEIDENT,   dbo.PREPAID.PECAIDENT, dbo.PREPAID.PEACT
      FROM
      dbo.HIA                                                                                 LEFT OUTER JOIN
      dbo.INVOICE                  ON     dbo.HIA.HIIVIDENT      = dbo.INVOICE.IVIDENT        LEFT OUTER JOIN
      dbo.AUTOMAT                  ON     dbo.HIA.HIAUIDENT      = dbo.AUTOMAT.AUIDENT        LEFT OUTER JOIN
      dbo.FUELSTAT                 ON     dbo.HIA.HIFUIDENT      = dbo.FUELSTAT.FUIDENT       LEFT OUTER JOIN
      dbo.ADDRESS                  ON     dbo.FUELSTAT.FUADIDENT = dbo.ADDRESS.ADIDENT        LEFT OUTER JOIN
      dbo.CARDS                    ON     dbo.HIA.HICAIDENT      = dbo.CARDS.CAIDENT          LEFT OUTER JOIN
      dbo.PREPAID                  ON     dbo.HIA.HICAIDENT      = dbo.PREPAID.PECAIDENT      LEFT OUTER JOIN
      dbo.COMPANY                  ON     dbo.CARDS.CACOIDENT    = dbo.COMPANY.COIDENT        LEFT OUTER JOIN
      dbo.ADDRESS   AS ADDRESS_3   ON     dbo.COMPANY.COADIDENT  = ADDRESS_3.ADIDENT          LEFT OUTER JOIN
      dbo.VEHICLE                  ON     dbo.HIA.HIVEIDENT      = dbo.VEHICLE.VEIDENT        LEFT OUTER JOIN
      dbo.VTECH                    ON     dbo.VEHICLE.VEIDENT    = dbo.VTECH.VTIDENT          LEFT OUTER JOIN
      dbo.COMPANY   AS COMPANY_2   ON     dbo.VEHICLE.VECOIDENT  = COMPANY_2.COIDENT          LEFT OUTER JOIN
      dbo.ADDRESS   AS ADDRESS_4   ON     COMPANY_2.COADIDENT    = ADDRESS_4.ADIDENT          LEFT OUTER JOIN
      dbo.CARDS     AS CARDS_2     ON     dbo.HIA.HICAIDENT2     = CARDS_2.CAIDENT            LEFT OUTER JOIN
      dbo.COMPANY   AS COMPANY_3   ON     CARDS_2.CACOIDENT      = COMPANY_3.COIDENT          LEFT OUTER JOIN
      dbo.STRUCTURE AS STRUCTURE_2 ON     dbo.VEHICLE.VELEIDENT  = STRUCTURE_2.SRIDENT        LEFT OUTER JOIN
      dbo.EMPLOYEE                 ON     dbo.HIA.HIEMIDENT      = dbo.EMPLOYEE.EMIDENT       LEFT OUTER JOIN
      dbo.COMPANY   AS COMPANY_1   ON     dbo.EMPLOYEE.EMCOIDENT = COMPANY_1.COIDENT          LEFT OUTER JOIN
      dbo.STRUCTURE AS STRUCTURE_1 ON     dbo.EMPLOYEE.EMLEIDENT = STRUCTURE_1.SRIDENT        LEFT OUTER JOIN
      dbo.ADDRESS   AS ADDRESS_2   ON     dbo.EMPLOYEE.EMADIDENT = ADDRESS_2.ADIDENT          LEFT OUTER JOIN
      dbo.ADDRESS   AS ADDRESS_5   ON     COMPANY_1.COADIDENT    = ADDRESS_5.ADIDENT          LEFT OUTER JOIN
      dbo.PBASE                    ON     dbo.HIA.HIPBIDENT      = dbo.PBASE.PBIDENT          LEFT OUTER JOIN
      dbo.PGROUP                   ON     dbo.PBASE.PBPGIDENT    = dbo.PGROUP.PGIDENT         LEFT OUTER JOIN
      dbo.PTYPE                    ON     dbo.PBASE.PBPTIDENT    = dbo.PTYPE.PTIDENT          LEFT OUTER JOIN
      dbo.FLEET                    ON     dbo.PBASE.PBTYPE       = dbo.FLEET.FENO             LEFT OUTER JOIN
      dbo.VAT                      ON     dbo.HIA.HIVAIDENT      = dbo.VAT.VAIDENT            LEFT OUTER JOIN
      dbo.STORAGE                  ON     dbo.HIA.HISTIDENT      = dbo.STORAGE.STIDENT        LEFT OUTER JOIN
      dbo.INPUTADD                 ON     dbo.HIA.HIIPIDENT      = dbo.inputadd.IPIDENT       LEFT OUTER JOIN
      dbo.ADISP                    ON     dbo.HIA.HIAIIDENT      = dbo.ADISP.AIIDENT          LEFT OUTER JOIN
      dbo.CARDS AS CARDS_3         ON     dbo.HIA.HIFLIDENT      = CARDS_3.CAIDENT            LEFT OUTER JOIN
      dbo.FCUNO                    ON     CARDS_3.CAFCIDENT      = dbo.FCUNO.FCIDENT          LEFT OUTER JOIN
      dbo.FLEET AS FLEET_2         ON     dbo.FCUNO.FCTYPE       = FLEET_2.FENO               LEFT OUTER JOIN
      dbo.EMPLOYEE as EMPLOYEE_1   ON     dbo.CARDS.CACOIDENT    = EMPLOYEE_1.EMCOID
      ORDER BY dbo.HIA.HITRDATE
    