
      CREATE VIEW [dbo].[VE_10]
      WITH  VIEW_METADATA
      AS
      SELECT     dbo.VEHICLE.VEIDENT, dbo.VEHICLE.VEDATE, dbo.VEHICLE.VEWHO, dbo.VEHICLE.VEINTNO, dbo.VEHICLE.VEPLATE, dbo.VEHICLE.VEMEMO,
      dbo.VEHICLE.VEPBIDENT, dbo.VEHICLE.VEPGIDENT, dbo.VEHICLE.VESTART, dbo.VEHICLE.VEEND, dbo.VEHICLE.VELEIDENT, dbo.VEHICLE.VECOIDENT,
      dbo.VEHICLE.VECC, dbo.VEHICLE.VEEMIDENT, dbo.VEHICLE.VESTOC, dbo.VEHICLE.VESRIDENT, dbo.VEHICLE.VEMILES, dbo.VEHICLE.VEHOURS,
      dbo.VEHICLE.VETYPE, dbo.VEHICLE.VEKMOFFSET, dbo.VEHICLE.VEHHOFFSET, dbo.VEHICLE.VEOFFDATE, dbo.VEHICLE.VEKMSTART, dbo.VEHICLE.VEHHSTART,
      dbo.VEHICLE.VEPLATE2, dbo.VEHICLE.VESTATE,   dbo.VEHICLE.VECOCODE,  dbo.VEHICLE.VEHO,      dbo.VEHICLE.VEDIVISION,dbo.VEHICLE.VEDIVABBR, dbo.VEHICLE.VEGROUP,dbo.VEHICLE.VECAT,
      dbo.USLOG.USIDENT, dbo.USLOG.USDATE, dbo.USLOG.USWHO, dbo.USLOG.USPW, dbo.USLOG.USNAME,
      dbo.STRUCTURE.SRNUMBER, dbo.STRUCTURE.SRTITLE, dbo.STRUCTURE.SRMEMO, dbo.STRUCTURE.SRADIDENT,
      dbo.ADDRESS.ADIDENT, dbo.ADDRESS.ADWHO,
      dbo.ADDRESS.ADDATE, dbo.ADDRESS.ADTYPE, dbo.ADDRESS.ADLOC, dbo.ADDRESS.ADZIP, dbo.ADDRESS.ADCTRY, dbo.ADDRESS.ADSTR, dbo.ADDRESS.ADHP,
      dbo.ADDRESS.ADPB, dbo.ADDRESS.ADFNAME1, dbo.ADDRESS.ADLNAME1, dbo.ADDRESS.ADTITLE1, dbo.ADDRESS.ADGEN1, dbo.ADDRESS.ADTEL1,
      dbo.ADDRESS.ADTEL2, dbo.ADDRESS.ADFAX1, dbo.ADDRESS.ADEMAIL1, dbo.ADDRESS.ADFNAME2, dbo.ADDRESS.ADLNAME2, dbo.ADDRESS.ADTITLE2,
      dbo.ADDRESS.ADGEN2, dbo.ADDRESS.ADTEL3, dbo.ADDRESS.ADTEL4, dbo.ADDRESS.ADFAX2, dbo.ADDRESS.ADEMAIL2, dbo.ADDRESS.ADBANK1,
      dbo.ADDRESS.ADROUTNO1, dbo.ADDRESS.ADIBAN1, dbo.ADDRESS.ADACC1, dbo.ADDRESS.ADIBC1, dbo.ADDRESS.ADBANK2, dbo.ADDRESS.ADROUTNO2,
      dbo.ADDRESS.ADIBAN2, dbo.ADDRESS.ADACC2, dbo.ADDRESS.ADIBC2, dbo.ADDRESS.ADXXIDENT, dbo.ADDRESS.ADVATID,
      dbo.PBASE.PBIDENT, dbo.PBASE.PBDATE, dbo.PBASE.PBWHO, dbo.PBASE.PBTITLE, dbo.PBASE.PBNUMBER,
      dbo.PBASE.PBMEMO, dbo.PBASE.PBPGIDENT, dbo.PBASE.PBPTIDENT, dbo.PBASE.PBEXTERN, dbo.PBASE.PBEAN, dbo.PBASE.PBDISPL, dbo.PBASE.PBVAIDENT,
      dbo.PGROUP.PGIDENT, dbo.PGROUP.PGDATE, dbo.PGROUP.PGWHO, dbo.PGROUP.PGTITLE, dbo.PGROUP.PGNUMBER, dbo.PGROUP.PGMEMO,
      dbo.VTECH.VTIDENT, dbo.VTECH.VTDATE, dbo.VTECH.VTWHO, dbo.VTECH.VTTANK, dbo.VTECH.VTNORM, dbo.VTECH.VTTYRESIZ1, dbo.VTECH.VTTYRESIZ2,
      dbo.VTECH.VTTYRESIZ3, dbo.VTECH.VTTYRESIZ4, dbo.VTECH.VTTYRESIZ5, dbo.VTECH.VTTYRESIZE, dbo.VTECH.VTSTEER1, dbo.VTECH.VTSTEER2,
      dbo.VTECH.VTSTEER3, dbo.VTECH.VTSTEER4, dbo.VTECH.VTSTEER5, dbo.VTECH.VTLIFT1, dbo.VTECH.VTLIFT2, dbo.VTECH.VTLIFT3, dbo.VTECH.VTLIFT4,
      dbo.VTECH.VTLIFT5, dbo.VTECH.VTTWIN1, dbo.VTECH.VTTWIN2, dbo.VTECH.VTTWIN3, dbo.VTECH.VTTWIN4, dbo.VTECH.VTTWIN5, dbo.VTECH.VTGVW,
      dbo.VTECH.VTSWL, dbo.VTECH.VTRET, dbo.VTECH.VTUNDA, dbo.VTECH.VTMOTOR, dbo.VTECH.VTMPOWER, dbo.VTECH.VTCYCLAP, dbo.VTECH.VTSEATS,
      dbo.VTECH.VTSTAND, dbo.VTECH.VTMEMO, dbo.VTECH.VTLOADAREA, dbo.VTECH.VTHOLD, dbo.VTECH.VTLOADH, dbo.VTECH.VTLOADW, dbo.VTECH.VTLOADL,
      dbo.VTECH.VTPOS,dbo.VTECH.VTNEG,
      dbo.COMPANY.COIDENT, dbo.COMPANY.CODATE, dbo.COMPANY.COWHO, dbo.COMPANY.COTYPE, dbo.COMPANY.COCONO1, dbo.COMPANY.COCONO2,
      dbo.COMPANY.COTITLE1, dbo.COMPANY.COTITLE2, dbo.COMPANY.COTITLE3, dbo.COMPANY.COMEMO, dbo.COMPANY.COADIDENT, dbo.COMPANY.COEND,
      dbo.COMPANY.COSTATE
      FROM
      dbo.VEHICLE LEFT OUTER JOIN
      dbo.USLOG      ON dbo.VEHICLE.VEWHO        = dbo.USLOG.USIDENT      LEFT OUTER JOIN
      dbo.STRUCTURE  ON dbo.VEHICLE.VELEIDENT    = dbo.STRUCTURE.SRIDENT  LEFT OUTER JOIN
      dbo.ADDRESS    ON dbo.STRUCTURE.SRADIDENT  = dbo.ADDRESS.ADIDENT    LEFT OUTER JOIN
      dbo.PBASE      ON dbo.VEHICLE.VEPBIDENT    = dbo.PBASE.PBIDENT      LEFT OUTER JOIN
      dbo.PGROUP     ON dbo.VEHICLE.VEPGIDENT    = dbo.PGROUP.PGIDENT     LEFT OUTER JOIN
      dbo.VTECH      ON dbo.VEHICLE.VEIDENT      = dbo.VTECH.VTIDENT      LEFT OUTER JOIN
      dbo.COMPANY    ON dbo.VEHICLE.VECOIDENT    = dbo.COMPANY.COIDENT
      WITH CHECK OPTION
    